function shop_init(){
	register_goods("large_fire",{"type":"card","cost":"10000","unlock_item_id":"large_fire","description":"大火炉：一次生产两朵火苗","display_name":"大火炉"})
	register_goods("iron_fishbone",{"type":"card","cost":"5000","unlock_item_id":"iron_fishbone","description":"钢鱼刺：攻击踩上它的老鼠，卡坏四次垃圾车","display_name":"钢鱼刺"})
	register_goods("gatlin_long_bao",{"type":"card","cost":"50000","unlock_item_id":"gatlin_long_bao","description":"机枪小笼包：发射四发包子","display_name":"机枪小笼包"})
	register_goods("rotating_coffee_pot",{"type":"card","cost":"50000","unlock_item_id":"rotating_coffee_pot","description":"旋转咖啡喷壶：3*3范围穿透攻击，白天睡觉","display_name":"旋转咖啡喷壶"})
	register_goods("takoyaki",{"type":"card","cost":"30000","unlock_item_id":"takoyaki","description":"章鱼烧：甩出两发追踪飞镖","display_name":"章鱼烧"})
	register_goods("ice_egg_boiler_pult",{"type":"card","cost":"30000","unlock_item_id":"ice_egg_boiler_pult","description":"冰煮蛋器：投掷减速冰鸡蛋","display_name":"冰煮蛋器"})
	register_goods("chocolate_cannon",{"type":"card","cost":"80000","unlock_item_id":"chocolate_cannon","description":"巧克力大炮：发射3*3范围爆炸的巧克力球","display_name":"巧克力大炮"})
	register_goods("firework_dragon",{"type":"card","cost":"80000","unlock_item_id":"firework_dragon","description":"花火龙：立即生产6朵火苗","display_name":"花火龙"})
	register_goods("gatlin_ice_long_bao",{"type":"card","cost":"20000","unlock_item_id":"gatlin_ice_long_bao","description":"机枪冰冻小笼包：发射四发冰包子","display_name":"机枪冰冻小笼包"})
	register_goods("aquarius_elve",{"type":"card","cost":"15000","unlock_item_id":"aquarius_elve","description":"水瓶座精灵：本行5格和本列5格范围爆炸","display_name":"水瓶座精灵"})
	register_goods("tar_sprayer",{"type":"card","cost":"80000","unlock_item_id":"tar_sprayer","description":"焦油喷壶：喷出可被点燃的油滴穿透攻击四格内敌人","display_name":"焦油喷壶"})
	register_goods("durian",{"type":"card","cost":"30000","unlock_item_id":"durian","description":"榴莲：伤害3*3范围敌人","display_name":"榴莲"})
	register_goods("dragon_fruit",{"type":"card","cost":"50000","unlock_item_id":"dragon_fruit","description":"火龙果：伤害3*3范围敌人","display_name":"火龙果"})
	register_goods("magic_chicken",{"type":"card","cost":"80000","unlock_item_id":"magic_chicken","description":"幻幻鸡：复制成上一张放置的卡片","display_name":"幻幻鸡"})
	register_goods("bull_firework",{"type":"card","cost":"50000","unlock_item_id":"bull_firework","description":"金牛烟花：召唤1只烟花牛冲撞敌人","display_name":"金牛烟花"})
	
	register_goods("card_slot_plus",{"type":"item","cost":"20000","unlock_item_id":"card_slot","description":"增加一格卡槽，仅可在卡槽数小于18时使用","display_name":"卡槽+1","spr":spr_slot_plus})
	register_goods("card_slot_19",{"type":"item","cost":"50000","unlock_item_id":"card_slot_19","description":"解锁第19格卡槽","display_name":"卡槽第19格","spr":spr_slot_19})
	register_goods("card_slot_20",{"type":"item","cost":"80000","unlock_item_id":"card_slot_20","description":"解锁第20格卡槽","display_name":"卡槽第20格","spr":spr_slot_20})
	register_goods("card_slot_21",{"type":"item","cost":"100000","unlock_item_id":"card_slot_21","description":"解锁第21格卡槽","display_name":"卡槽第21格","spr":spr_slot_21})
	
	register_goods("howitzer",{"type":"weapon","cost":"20000","unlock_item_id":"howitzer","description":"榴弹炮：自动发射高伤害榴弹","display_name":"榴弹炮"})
	register_goods("enhanced_howitzer",{"type":"weapon","cost":"50000","unlock_item_id":"enhanced_howitzer","description":"加强榴弹炮：自动发射两个高伤害榴弹","display_name":"加强榴弹炮"})
	register_goods("mighty_gun",{"type":"weapon","cost":"15000","unlock_item_id":"mighty_gun","description":"威武枪：发射四发子弹","display_name":"威武枪"})
	register_goods("cat_gun",{"type":"weapon","cost":"50000","unlock_item_id":"cat_gun","description":"猫猫枪：发射能惊吓敌人的猫猫弹","display_name":"猫猫枪"})
	register_goods("cut_cake_shield",{"type":"weapon","cost":"8000","unlock_item_id":"cut_cake_shield","description":"切糕盾牌：增加300生命值","display_name":"切糕盾牌"})
	register_goods("starlight_gem",{"type":"gem","cost":"30000","unlock_item_id":"starlight_gem","description":"星光宝石：召唤星星压扁老鼠并产生火苗","display_name":"星光宝石"})
	register_goods("flame_recover_gem",{"type":"gem","cost":"50000","unlock_item_id":"flame_recover_gem","description":"回火宝石：从天上掉落火苗","display_name":"回火宝石"})
	register_goods("power_gem",{"type":"gem","cost":"15000","unlock_item_id":"power_gem","description":"强力宝石：增加超级武器伤害","display_name":"强力宝石"})
	register_goods("gale_gem",{"type":"gem","cost":"50000","unlock_item_id":"gale_gem","description":"疾风宝石：增加超级武器攻速","display_name":"疾风宝石"})
	register_goods("transform_gem",{"type":"gem","cost":"50000","unlock_item_id":"transform_gem","description":"转化宝石：子弹落地产生火苗","display_name":"转化宝石"})
	register_goods("bleed_gem",{"type":"gem","cost":"20000","unlock_item_id":"bleed_gem","description":"流血宝石：伤害周围敌人","display_name":"流血宝石"})
	register_goods("guard_gem",{"type":"gem","cost":"20000","unlock_item_id":"guard_gem","description":"守护宝石：治疗周围卡片并增加生命上限","display_name":"守护宝石"})
	register_goods("strength_gem",{"type":"gem","cost":"50000","unlock_item_id":"strength_gem","description":"蓄力宝石：增加周围卡片伤害","display_name":"蓄力宝石"})
	register_goods("ice_spoon_crossbow",{"type":"weapon","cost":"20000","unlock_item_id":"ice_spoon_crossbow","description":"冰勺弩枪：投掷减速冰鸡蛋","display_name":"冰勺弩枪"})
	register_goods("poseidon_dart_gun",{"type":"weapon","cost":"80000","unlock_item_id":"poseidon_dart_gun","description":"海神镖枪：发射两个追踪飞镖攻击敌人","display_name":"海神镖枪"})
	
	register_goods("ice_egg_pisces",{"type":"card_attire","cost":"50000","unlock_item_id":"ice_egg_pisces","description":"冰煮蛋器投手的双鱼座精灵时装","display_name":"冰蛋星座时装"})
	register_goods("water_pipe_libra",{"type":"card_attire","cost":"50000","unlock_item_id":"water_pipe_libra","description":"双向水管的天秤座精灵时装","display_name":"水管星座时装"})
	register_goods("wine_rack_sagittarius",{"type":"card_attire","cost":"50000","unlock_item_id":"wine_rack_sagittarius","description":"三线酒架的射手座精灵时装","display_name":"酒架星座时装"})
	register_goods("brazier_taurus",{"type":"card_attire","cost":"50000","unlock_item_id":"brazier_taurus","description":"火盆的金牛座精灵时装","display_name":"火盆星座时装"})
	register_goods("large_fire_gemini",{"type":"card_attire","cost":"50000","unlock_item_id":"large_fire_gemini","description":"大火炉的双子座精灵时装","display_name":"大火星座时装"})
	register_goods("takoyaki_cancer",{"type":"card_attire","cost":"50000","unlock_item_id":"takoyaki_cancer","description":"章鱼烧的巨蟹座精灵时装","display_name":"章鱼星座时装"})
	register_goods("gatling_popcorn",{"type":"card_attire","cost":"50000","unlock_item_id":"gatling_popcorn","description":"机枪小笼包的玉蜀黍时装","display_name":"机枪玉米时装"})
	register_goods("rotate_leo",{"type":"card_attire","cost":"50000","unlock_item_id":"rotate_leo","description":"旋转咖啡喷壶的狮子座精灵时装","display_name":"旋转星座时装"})
	register_goods("melon_virgo",{"type":"card_attire","cost":"50000","unlock_item_id":"melon_virgo","description":"瓜皮护罩的处女座精灵时装","display_name":"瓜皮星座时装"})
	
	register_goods("player_attire_1",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_1","description":"角色的雪球兔兔时装","display_name":"雪球兔兔"})
	register_goods("player_attire_2",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_2","description":"角色的提拉米苏时装","display_name":"提拉米苏"})
	register_goods("player_attire_3",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_3","description":"角色的魔影圣衣时装","display_name":"魔影圣衣"})
	register_goods("player_attire_4",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_4","description":"角色的公会制服时装","display_name":"公会制服"})
	register_goods("player_attire_5",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_5","description":"角色的龙族传说时装","display_name":"龙族传说"})
	register_goods("player_attire_6",{"type":"player_attire","cost":"50000","unlock_item_id":"player_attire_6","description":"角色的神奇精灵时装","display_name":"神奇精灵"})
	register_goods("player_attire_s",{"type":"player_attire","cost":"100000","unlock_item_id":"player_attire_s","description":"角色的星之焕变身时装","display_name":"星之焕"})
}