instance_destroy(obj_gods_store_closer)
instance_destroy(obj_gods_store_buy_btn)
instance_destroy(obj_gods_store_select_btn)
instance_destroy(obj_gods_store_page_btn)
obj_gods_hall_bg.is_submenu_opened = false