function attire_registry_init(){
	global.attire_pool = ds_map_create()
}

///@function get_attire_info(attire_id)
///@description 获取时装数据
///@param {string}attire_id 时装id
///@return {struct}
function get_attire_info(attire_id){
	return ds_map_find_value(global.attire_pool,attire_id)
}

///@function register_attire(attire_id,attire_data)
///@description 注册时装
///@param {string}attire_id 时装id
///@param {struct}attire_data 时装数据
function register_attire(attire_id,attire_data){
	ds_map_add(global.attire_pool,attire_id,attire_data)
}


function attire_init(){
	attire_registry_init()
	//注册全部卡片时装
	register_attire(
		"ice_egg_pisces",
		{
			"target_card":"egg_boiler_pult",
			"name":"双鱼座精灵",
			"icon":spr_ice_egg_pisces_icon,
			"spr":[spr_ice_egg_pisces,spr_ice_egg_pisces_1,spr_ice_egg_pisces_2],
			"card_slot_icon":[spr_ice_egg_pisces_icon,spr_ice_egg_pisces_icon_1,spr_ice_egg_pisces_icon_2],
			"card_overrides":{
				"0":{"cost":200,"is_special":1,"description":"双鱼座精灵：投掷冰鱼并产生溅射伤害，威力强大！"},
				"1":{"cost":200,"is_special":1,"description":"双鱼座战将：投掷强力冰鱼并产生溅射伤害，威力强大！"},
				"2":{"cost":200,"is_special":1,"description":"双鱼座星宿：投掷两发强力冰鱼并产生溅射伤害，威力强大！"}
			},
			"name_overrides":{
				"0":"双鱼座精灵",
				"1":"双鱼座战将",
				"2":"双鱼座星宿"
			}
		}
	)
	register_attire(
		"water_pipe_libra",
		{
			"target_card":"double_water_pipe",
			"name":"天秤座精灵",
			"icon":spr_water_pipe_libra,
			"spr":[spr_water_pipe_libra,spr_water_pipe_libra_1,spr_water_pipe_libra_2],
			"card_slot_icon":[spr_water_pipe_libra,spr_water_pipe_libra_1,spr_water_pipe_libra_2],
			"card_overrides":{
				"0":{"cost":150,"is_special":1,"description":"天秤座精灵：对前后方各发射3发子弹，威力与实力的象征！"},
				"1":{"cost":150,"is_special":1,"description":"天秤座战将：对前后方各发射3发强力子弹，威力与实力的象征！"},
				"2":{"cost":150,"is_special":1,"description":"天秤座星宿：对前后方各发射4发强力子弹，威力与实力的象征！"}
			},
			"name_overrides":{
				"0":"天秤座精灵",
				"1":"天秤座战将",
				"2":"天秤座星宿"
			}
		}
	)
	register_attire(
		"wine_rack_sagittarius",
		{
			"target_card":"triple_wine_rack",
			"name":"射手座精灵",
			"icon":spr_wine_rack_sagittarius_icon,
			"spr":[spr_wine_rack_sagittarius,spr_wine_rack_sagittarius_1,spr_wine_rack_sagittarius_2],
			"card_slot_icon":[spr_wine_rack_sagittarius_icon,spr_wine_rack_sagittarius_icon_1,spr_wine_rack_sagittarius_icon_2],
			"card_overrides":{
				"0":{"cost":300,"is_special":1,"description":"射手座精灵：向正前方三行射出4发子弹，威力巨大！"},
				"1":{"cost":300,"is_special":1,"description":"射手座战将：向正前方三行射出4发子弹，威力巨大！"},
				"2":{"cost":300,"is_special":1,"description":"射手座星宿：向正前方三行射出6发子弹，威力巨大！"}
			},
			"name_overrides":{
				"0":"射手座精灵",
				"1":"射手座战将",
				"2":"射手座星宿"
			}
		}
	)
	register_attire(
		"brazier_taurus",
		{
			"target_card":"brazier",
			"name":"金牛座精灵",
			"icon":spr_brazier_taurus,
			"spr":[spr_brazier_taurus,spr_brazier_taurus_1,spr_brazier_taurus_2],
			"card_slot_icon":[spr_brazier_taurus,spr_brazier_taurus_1,spr_brazier_taurus_2],
		"card_overrides":{
				"0":{"cost":225,"is_special":1,"description":"金牛座精灵：点燃子弹，威力大幅提升"},
				"1":{"cost":175,"is_special":1,"description":"金牛座战将：点燃子弹，威力大幅提升"},
				"2":{"cost":175,"is_special":1,"description":"金牛座星宿：点燃子弹，威力大幅提升"}
			},
			"name_overrides":{
				"0":"金牛座精灵",
				"1":"金牛座战将",
				"2":"金牛座星宿"
			}
		}
	)
	register_attire(
		"large_fire_gemini",
		{
			"target_card":"large_fire",
			"name":"双子座精灵",
			"icon":spr_large_fire_gemini_icon,
			"spr":[spr_large_fire_gemini,spr_large_fire_gemini_1,spr_large_fire_gemini_2],
			"card_slot_icon":[spr_large_fire_gemini_icon,spr_large_fire_gemini_icon_1,spr_large_fire_gemini_icon_2],
			"card_overrides":{
				"0":{"cost":200,"is_special":1,"description":"双子座精灵：能量产生近乎达到极限，可同时产出4朵火苗"},
				"1":{"cost":200,"is_special":1,"description":"双子座战将：能量产生近乎达到极限，可同时产出4朵火苗","cooldown":15*60},
				"2":{"cost":200,"is_special":1,"description":"双子座星宿：能量产生近乎达到极限，可同时产出6朵火苗","cooldown":15*60}
			},
			"name_overrides":{
				"0":"双子座精灵",
				"1":"双子座战将",
				"2":"双子座星宿"
			}
		}
	)
	register_attire(
		"takoyaki_cancer",
		{
			"target_card":"takoyaki",
			"name":"巨蟹座精灵",
			"icon":spr_takoyaki_cancer_icon,
			"spr":[spr_takoyaki_cancer,spr_takoyaki_cancer_1,spr_takoyaki_cancer_2],
			"card_slot_icon":[spr_takoyaki_cancer_icon,spr_takoyaki_cancer_icon_1,spr_takoyaki_cancer_icon_2],
			"card_overrides":{
				"0":{"cost":225,"is_special":1,"description":"巨蟹座精灵：扔出4发大钳子，全屏跟踪，无死角攻击！"},
				"1":{"cost":225,"is_special":1,"description":"巨蟹座战将：扔出4发强力大钳子，全屏跟踪，无死角攻击！"},
				"2":{"cost":225,"is_special":1,"description":"巨蟹座星宿：扔出6发强力大钳子，全屏跟踪，无死角攻击！"}
			},
			"name_overrides":{
				"0":"巨蟹座精灵",
				"1":"巨蟹座战将",
				"2":"巨蟹座星宿"
			}
		}
	)
	register_attire(
		"gatling_popcorn",
		{
			"target_card":"gatlin_long_bao",
			"name":"玉蜀黍",
			"icon":spr_gatling_popcorn_icon,
			"spr":[spr_gatling_popcorn,spr_gatling_popcorn_1,spr_gatling_popcorn_2],
			"card_slot_icon":[spr_gatling_popcorn_icon,spr_gatling_popcorn_icon_1,spr_gatling_popcorn_icon_2],
		"card_overrides":{
				"0":{"cost":250,"is_special":1,"description":"玉蜀黍：射速极高的机枪"},
				"1":{"cost":250,"is_special":1,"description":"奶油玉蜀黍：射速极高的机枪"},
				"2":{"cost":250,"is_special":1,"description":"加农玉蜀黍：射速极高的机枪"}
			},
			"name_overrides":{
				"0":"玉蜀黍",
				"1":"奶油玉蜀黍",
				"2":"加农玉蜀黍"
			}
		}
	)
	register_attire(
		"rotate_leo",
		{
			"target_card":"rotating_coffee_pot",
			"name":"狮子座精灵",
			"icon":spr_rotate_leo_icon,
			"spr":[spr_rotate_leo,spr_rotate_leo_1,spr_rotate_leo_2],
			"card_slot_icon":[spr_rotate_leo_icon,spr_rotate_leo_icon_1,spr_rotate_leo_icon_2],
			"card_overrides":{
				"0":{"cost":275,"is_special":1,"description":"狮子座精灵：连续快速向周边发出猛烈攻击，海陆空交通管制！"},
				"1":{"cost":275,"is_special":1,"description":"狮子座战将：连续快速向周边发出猛烈攻击，海陆空交通管制！"},
				"2":{"cost":275,"is_special":1,"description":"狮子座星宿：连续快速向周边发出猛烈攻击，海陆空交通管制！","cooldown":30*60}
			},
			"name_overrides":{
				"0":"狮子座精灵",
				"1":"狮子座战将",
				"2":"狮子座星宿"
			}
		}
	)
	register_attire(
		"melon_virgo",
		{
			"target_card":"melon_shield",
			"name":"处女座精灵",
			"icon":spr_melon_virgo_icon,
			"spr":[spr_melon_virgo_icon,spr_melon_virgo_icon_1,spr_melon_virgo_icon_2],
			"outer_spr":[
				[spr_melon_virgo_outer_1,spr_melon_virgo_outer_1,spr_melon_virgo_outer_1],
				[spr_melon_virgo_1_outer_1,spr_melon_virgo_1_outer_2,spr_melon_virgo_1_outer_3],
				[spr_melon_virgo_2_outer_1,spr_melon_virgo_2_outer_2,spr_melon_virgo_2_outer_3]
			],
			"card_slot_icon":[spr_melon_virgo_icon,spr_melon_virgo_icon_1,spr_melon_virgo_icon_2],
			"inner_spr":[spr_melon_virgo_inner_1,spr_melon_virgo_inner_2,spr_melon_virgo_inner_3],
			"card_overrides":{
				"0":{"cost":175,"is_special":1,"description":"处女座精灵：保护被它罩住的卡片，体力更高！"},
				"1":{"cost":200,"is_special":1,"description":"处女座战将：保护被它罩住的卡片，体力更高！"},
				"2":{"cost":225,"is_special":1,"description":"处女座星宿：保护被它罩住的卡片，体力更高！"}
			},
			"name_overrides":{
				"0":"处女座精灵",
				"1":"处女座战将",
				"2":"处女座星宿"
			}
		}
	)
	register_attire(
		"bubble_maltose",
		{
			"target_card":"soda_bubble",
			"name":"麦芽糖",
			"icon":spr_bubble_maltose_icon,
			"spr":[spr_bubble_maltose_0_0,spr_bubble_maltose_1_0],
			"card_slot_icon":[spr_bubble_maltose_icon,spr_bubble_maltose_icon_1],
		}
	)
	
	//注册全部玩家时装
	register_attire(
		"player_attire_1",
		{
			"target_card":"player",
			"name":"雪球兔兔",
			"icon":spr_player_attire_1_icon,
			"spr":spr_player_attire_1,
		}
	)
	register_attire(
		"player_attire_2",
		{
			"target_card":"player",
			"name":"提拉米苏",
			"icon":spr_player_attire_2_icon,
			"spr":spr_player_attire_2,
		}
	)
	register_attire(
		"player_attire_3",
		{
			"target_card":"player",
			"name":"魔影圣衣",
			"icon":spr_player_attire_3_icon,
			"spr":spr_player_attire_3,
		}
	)
	register_attire(
		"player_attire_4",
		{
			"target_card":"player",
			"name":"公会制服",
			"icon":spr_player_attire_4_icon,
			"spr":spr_player_attire_4,
		}
	)
	register_attire(
		"player_attire_5",
		{
			"target_card":"player",
			"name":"龙族传说",
			"icon":spr_player_attire_5_icon,
			"spr":spr_player_attire_5,
		}
	)
	register_attire(
		"player_attire_6",
		{
			"target_card":"player",
			"name":"神奇精灵",
			"icon":spr_player_attire_6_icon,
			"spr":spr_player_attire_6,
		}
	)
	register_attire(
		"player_attire_a",
		{
			"target_card":"player",
			"name":"星轨织梦",
			"icon":spr_player_attire_a_icon,
			"spr":spr_player_attire_a,
		}
	)
	register_attire(
		"player_attire_b",
		{
			"target_card":"player",
			"name":"红桃爱丽丝",
			"icon":spr_player_attire_b_icon,
			"spr":spr_player_attire_b,
		}
	)
	register_attire(
		"player_attire_s",
		{
			"target_card":"player",
			"name":"星之焕",
			"icon":spr_player_attire_s_icon,
			"spr":spr_player_attire_s,
		}
	)
	register_attire(
		"player_attire_7",
		{
			"target_card":"player",
			"name":"双子座情人",
			"icon":spr_player_attire_7_icon,
			"spr":spr_player_attire_7,
		}
	)
	register_attire(
		"player_attire_8",
		{
			"target_card":"player",
			"name":"双子座情人",
			"icon":spr_player_attire_8_icon,
			"spr":spr_player_attire_8,
		}
	)
	register_attire(
		"player_attire_9",
		{
			"target_card":"player",
			"name":"爱莎鼠同人",
			"icon":spr_player_attire_9_icon,
			"spr":spr_player_attire_9,
		}
	)
	register_attire(
		"player_attire_10",
		{
			"target_card":"player",
			"name":"别西卜",
			"icon":spr_player_attire_10_icon,
			"spr":spr_player_attire_10,
		}
	)
	register_attire(
		"player_attire_11",
		{
			"target_card":"player",
			"name":"冰淇淋小姐",
			"icon":spr_player_attire_11_icon,
			"spr":spr_player_attire_11,
		}
	)
	register_attire(
		"player_attire_12",
		{
			"target_card":"player",
			"name":"丁香绮缘",
			"icon":spr_player_attire_12_icon,
			"spr":spr_player_attire_12,
		}
	)
	register_attire(
		"player_attire_13",
		{
			"target_card":"player",
			"name":"梦恋花语",
			"icon":spr_player_attire_13_icon,
			"spr":spr_player_attire_13,
		}
	)
	register_attire(
		"player_attire_14",
		{
			"target_card":"player",
			"name":"探险家",
			"icon":spr_player_attire_14_icon,
			"spr":spr_player_attire_14,
		}
	)
}