function maps_init(){
	map_registry_init()
	register_map("delicious_island",{"map_name":"美味岛","map_sprite":spr_delicious_islands,"levels_data":[{"id":"salad_island_land","name":"色拉岛（陆）","button_spr":spr_levelselect_button,"button_index":1,"button_x":1365,"button_y":455,"level_file":"salad_island_land.json","hard_level_file":"salad_island_land_hard.json","level_sprite":spr_salad_island_land,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":2,"pre_level_require":[]},
																										{"id":"salad_island_water","name":"色拉岛（水）","button_spr":spr_levelselect_button,"button_index":2,"button_x":1395,"button_y":620,"level_file":"salad_island_water.json","hard_level_file":"salad_island_water_hard.json","level_sprite":spr_salad_island_water,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":3,"pre_level_require":[]},
																										{"id":"cookie_island","name":"曲奇岛","button_spr":spr_levelselect_button,"button_index":0,"button_x":1295,"button_y":285,"level_file":"cookie_island.json","hard_level_file":"cookie_island_hard.json","level_sprite":spr_cookie_island,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":1,"pre_level_require":[]},
																										{"id":"mousse_island","name":"慕斯岛","button_spr":spr_levelselect_button,"button_index":3,"button_x":1310,"button_y":730,"level_file":"mousse_island.json","hard_level_file":"mousse_island_hard.json","level_sprite":spr_mousse_island,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":4,"pre_level_require":[]},
																										{"id":"champagne_island_land","name":"香槟岛（陆）","button_spr":spr_levelselect_button,"button_index":4,"button_x":1070,"button_y":833,"level_file":"champagne_island_land.json","hard_level_file":"champagne_island_land_hard.json","level_sprite":spr_champagne_island_land,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":5,"pre_level_require":[]},
																										{"id":"champagne_island_water","name":"香槟岛（水）","button_spr":spr_levelselect_button,"button_index":5,"button_x":885,"button_y":765,"level_file":"champagne_island_water.json","hard_level_file":"champagne_island_water_hard.json","level_sprite":spr_champagne_island_water,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":6,"pre_level_require":[]},
																										{"id":"temple","name":"神殿","button_spr":spr_levelselect_button,"button_index":6,"button_x":630,"button_y":720,"level_file":"temple.json","hard_level_file":"temple_hard.json","level_sprite":spr_temple,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":7,"pre_level_require":[]},
																										{"id":"pudding_island_daytime","name":"布丁岛（日）","button_spr":spr_levelselect_button,"button_index":7,"button_x":405,"button_y":715,"level_file":"pudding_island_daytime.json","hard_level_file":"pudding_island_daytime_hard.json","level_sprite":spr_pudding_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":9,"pre_level_require":[]},
																										{"id":"pudding_island_night","name":"布丁岛（夜）","button_spr":spr_levelselect_button,"button_index":8,"button_x":285,"button_y":585,"level_file":"pudding_island_night.json","hard_level_file":"pudding_island_night_hard.json","level_sprite":spr_pudding_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":10,"pre_level_require":[]},
																										{"id":"cocoa_island_daytime","name":"可可岛（日）","button_spr":spr_levelselect_button,"button_index":9,"button_x":335,"button_y":475,"level_file":"cocoa_island_daytime.json","hard_level_file":"cocoa_island_daytime_hard.json","level_sprite":spr_cocoa_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":11,"pre_level_require":[]},
																										{"id":"cocoa_island_night","name":"可可岛（夜）","button_spr":spr_levelselect_button,"button_index":10,"button_x":375,"button_y":365,"level_file":"cocoa_island_night.json","hard_level_file":"cocoa_island_night_hard.json","level_sprite":spr_cocoa_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":12,"pre_level_require":[]},
																										{"id":"curry_island_daytime","name":"咖喱岛（日）","button_spr":spr_levelselect_button,"button_index":11,"button_x":455,"button_y":255,"level_file":"curry_island_daytime.json","hard_level_file":"curry_island_daytime_hard.json","level_sprite":spr_curry_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":13,"pre_level_require":[]},
																										{"id":"curry_island_night","name":"咖喱岛（夜）","button_spr":spr_levelselect_button,"button_index":12,"button_x":578,"button_y":215,"level_file":"curry_island_night.json","hard_level_file":"curry_island_night_hard.json","level_sprite":spr_curry_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":14,"pre_level_require":[]},
																										{"id":"abyss","name":"深渊岛","button_spr":spr_levelselect_button,"button_index":13,"button_x":750,"button_y":135,"level_file":"abyss.json","hard_level_file":"abyss_hard.json","level_sprite":spr_abyss,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":15,"pre_level_require":[]},
																										{"id":"tower_cake","name":"深渊岛","button_spr":spr_levelselect_button,"button_index":14,"button_x":1075,"button_y":510,"level_file":"abyss.json","hard_level_file":"abyss_hard.json","level_sprite":spr_abyss,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":8,"pre_level_require":[]},
	]})
	
	register_map(
		"tower_cake",
		{
			"map_name":"魔塔蛋糕",
			"map_sprite":spr_tower_cake_bg,
			"levels_data":[
				{
					"id":"tower_cake_1_1",
					"name":"魔塔1层-先锋",
					"level_file":"tower/tower-1-1.json",
					"hard_level_file":"tower/tower-1-1_hard.json",
					"level_sprite":spr_salad_island_land,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"none",
					"rewards":[
						{"card_id":"wooden_plate","target_shape":1}
					]
				},
				{
					"id":"tower_cake_1_2",
					"name":"魔塔1层-精英",
					"level_file":"tower/tower-1-2.json",
					"hard_level_file":"tower/tower-1-2_hard.json",
					"level_sprite":spr_salad_island_land,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_1_1",
					"rewards":[
						{"card_id":"oil_lamp","target_shape":1}
					]
				},
				{
					"id":"tower_cake_2_1",
					"name":"魔塔2层-先锋",
					"level_file":"tower/tower-2-1.json",
					"hard_level_file":"tower/tower-2-1_hard.json",
					"level_sprite":spr_mousse_island,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_1_2",
					"rewards":[
						{"card_id":"goblet_lamp","target_shape":1},
						{"card_id":"chocolate_cannon","target_shape":1}
					]
				},
				{
					"id":"tower_cake_2_2",
					"name":"魔塔2层-精英",
					"level_file":"tower/tower-2-2.json",
					"hard_level_file":"tower/tower-2-2_hard.json",
					"level_sprite":spr_mousse_island,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_2_1",
					"rewards":[
						{"card_id":"gatlin_long_bao","target_shape":1}
					]
				},
				{
					"id":"tower_cake_3_1",
					"name":"魔塔3层-先锋",
					"level_file":"tower/tower-3-1.json",
					"hard_level_file":"tower/tower-3-1_hard.json",
					"level_sprite":spr_temple,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_2_2",
					"rewards":[
						{"card_id":"iron_fishbone","target_shape":1},
						{"card_id":"coffee_cup","target_shape":1}
					]
				},
				{
					"id":"tower_cake_3_2",
					"name":"魔塔3层-精英",
					"level_file":"tower/tower-3-2.json",
					"hard_level_file":"tower/tower-3-2_hard.json",
					"level_sprite":spr_temple,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_3_1",
					"rewards":[
						{"card_id":"rotating_coffee_pot","target_shape":1}
					]
				},
				{
					"id":"tower_cake_4_1",
					"name":"魔塔4层-先锋",
					"level_file":"tower/tower-4-1.json",
					"hard_level_file":"tower/tower-4-1_hard.json",
					"level_sprite":spr_cocoa_island_daytime,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_3_2",
					"rewards":[
						{"card_id":"takoyaki","target_shape":1},
						{"card_id":"chocolate_bread","target_shape":1}
					]
				},
				{
					"id":"tower_cake_4_2",
					"name":"魔塔4层-精英",
					"level_file":"tower/tower-4-2.json",
					"hard_level_file":"tower/tower-4-2_hard.json",
					"level_sprite":spr_cocoa_island_daytime,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_4_1",
					"rewards":[
						{"card_id":"large_fire","target_shape":1}
					]
				},
				{
					"id":"tower_cake_5_1",
					"name":"魔塔5层-先锋",
					"level_file":"tower/tower-5-1.json",
					"hard_level_file":"tower/tower-5-1_hard.json",
					"level_sprite":spr_cocoa_island_night,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_4_2",
					"rewards":[
						{"card_id":"small_fire","target_shape":1}
					]
				},
				{
					"id":"tower_cake_5_2",
					"name":"魔塔5层-精英",
					"level_file":"tower/tower-5-2.json",
					"hard_level_file":"tower/tower-5-2_hard.json",
					"level_sprite":spr_cocoa_island_night,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_5_1",
					"rewards":[
						{"card_id":"ice_egg_boiler_pult","target_shape":1},
						{"card_id":"coffee_pot","target_shape":1}
					]
				},
				{
					"id":"tower_cake_6_1",
					"name":"魔塔6层-先锋",
					"level_file":"tower/tower-6-1.json",
					"hard_level_file":"tower/tower-6-1_hard.json",
					"level_sprite":spr_abyss,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_5_2",
					"rewards":[
						{"card_id":"cherry_pudding","target_shape":1}
					]
				},
				{
					"id":"tower_cake_6_2",
					"name":"魔塔6层-精英",
					"level_file":"tower/tower-6-2.json",
					"hard_level_file":"tower/tower-6-2_hard.json",
					"level_sprite":spr_abyss,
					"pre_music":mus_delicious_tower_pre,
					"elite_music":mus_delicious_tower_elite,
					"boss_music":mus_delicious_tower_boss,
					"pre_level":"tower_cake_6_1",
					"rewards":[
						{"card_id":"melon_shield","target_shape":1},
						{"card_id":"double_water_pipe","target_shape":1}
					]
				},
				{
					"id":"tower_cake_7_1",
					"name":"魔塔7层-先锋",
					"level_file":"tower/tower-7-1.json",
					"hard_level_file":"tower/tower-7-1_hard.json",
					"level_sprite":spr_mustard_cottage_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_6_2",
					"rewards":[
						{"card_id":"chocolate_pult","target_shape":1},
						{"card_id":"mouse_clip","target_shape":1}
					]
				},
				{
					"id":"tower_cake_7_2",
					"name":"魔塔7层-精英",
					"level_file":"tower/tower-7-2.json",
					"hard_level_file":"tower/tower-7-2_hard.json",
					"level_sprite":spr_mustard_cottage_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_7_1",
					"rewards":[
						{"card_id":"triple_wine_rack","target_shape":1}
					]
				},
				{
					"id":"tower_cake_8_1",
					"name":"魔塔8层-先锋",
					"level_file":"tower/tower-8-1.json",
					"hard_level_file":"tower/tower-8-1_hard.json",
					"level_sprite":spr_mint_beach_daytime_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_7_2",
					"rewards":[
						{"card_id":"salad_pult","target_shape":1},
						{"card_id":"durian","target_shape":1}
					]
				},
				{
					"id":"tower_cake_8_2",
					"name":"魔塔8层-精英",
					"level_file":"tower/tower-8-2.json",
					"hard_level_file":"tower/tower-8-2_hard.json",
					"level_sprite":spr_mint_beach_daytime_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_8_1",
					"rewards":[
						{"card_id":"brazier","target_shape":1},
						{"card_id":"coffee_grounds","target_shape":1}
					]
				},
				{
					"id":"tower_cake_9_1",
					"name":"魔塔9层-先锋",
					"level_file":"tower/tower-9-1.json",
					"hard_level_file":"tower/tower-9-1_hard.json",
					"level_sprite":spr_mint_beach_night_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_8_2",
					"rewards":[
						{"card_id":"stinky_tofu_pult","target_shape":1}
					]
				},
				{
					"id":"tower_cake_9_2",
					"name":"魔塔9层-精英",
					"level_file":"tower/tower-9-2.json",
					"hard_level_file":"tower/tower-9-2_hard.json",
					"level_sprite":spr_mint_beach_night_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_9_1",
					"rewards":[
						{"card_id":"egg_boiler_pult","target_shape":1}
					]
				},
				{
					"id":"tower_cake_10_1",
					"name":"魔塔10层-先锋",
					"level_file":"tower/tower-10-1.json",
					"hard_level_file":"tower/tower-10-1_hard.json",
					"level_sprite":spr_cheese_castle,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_9_2",
					"rewards":[
						{"card_id":"firework_dragon","target_shape":1}
					]
				},
				{
					"id":"tower_cake_10_2",
					"name":"魔塔10层-精英",
					"level_file":"tower/tower-10-2.json",
					"hard_level_file":"tower/tower-10-2_hard.json",
					"level_sprite":spr_cheese_castle,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_10_1",
					"rewards":[
						{"card_id":"hamburger","target_shape":1}
					]
				},
				{
					"id":"tower_cake_11_1",
					"name":"魔塔11层-先锋",
					"level_file":"tower/tower-11-1.json",
					"hard_level_file":"tower/tower-11-1_hard.json",
					"level_sprite":spr_charcoal_jungle_daytime_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_10_2",
					"rewards":[
						{"card_id":"hotdog_cannon","target_shape":1},
						{"card_id":"dragon_fruit","target_shape":1}
					]
				},
				{
					"id":"tower_cake_11_2",
					"name":"魔塔11层-精英",
					"level_file":"tower/tower-11-2.json",
					"hard_level_file":"tower/tower-11-2_hard.json",
					"level_sprite":spr_charcoal_jungle_daytime_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_11_1",
					"rewards":[
						{"card_id":"tar_sprayer","target_shape":1}
					]
				},
				{
					"id":"tower_cake_12_1",
					"name":"魔塔12层-先锋",
					"level_file":"tower/tower-12-1.json",
					"hard_level_file":"tower/tower-12-1_hard.json",
					"level_sprite":spr_charcoal_jungle_night_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_11_2",
					"rewards":[
						{"card_id":"oden_pot","target_shape":1}
					]
				},
				{
					"id":"tower_cake_12_2",
					"name":"魔塔12层-精英",
					"level_file":"tower/tower-12-2.json",
					"hard_level_file":"tower/tower-12-2_hard.json",
					"level_sprite":spr_charcoal_jungle_night_tower,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_12_1",
					"rewards":[
						{"card_id":"cotton_candy","target_shape":1}
					]
				},
				{
					"id":"tower_cake_13_1",
					"name":"魔塔13层-先锋",
					"level_file":"tower/tower-13-1.json",
					"hard_level_file":"tower/tower-13-1_hard.json",
					"level_sprite":spr_matcha_manor_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_12_2",
					"rewards":[
						{"card_id":"flour_sack","target_shape":1}
					]
				},
				{
					"id":"tower_cake_13_2",
					"name":"魔塔13层-精英",
					"level_file":"tower/tower-13-2.json",
					"hard_level_file":"tower/tower-13-2_hard.json",
					"level_sprite":spr_matcha_manor_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_13_1",
					"rewards":[
						{"card_id":"coke_bomb","target_shape":1},
						{"card_id":"ventilation_fan","target_shape":1}
					]
				},
				{
					"id":"tower_cake_14_1",
					"name":"魔塔14层-先锋",
					"level_file":"tower/tower-14-1.json",
					"hard_level_file":"tower/tower-14-1_hard.json",
					"level_sprite":spr_matcha_manor_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_13_2",
					"rewards":[
						{"card_id":"wine_bottle_bomb","target_shape":1},
						{"card_id":"xinjiang_fried_noodles","target_shape":1}
					]
				},
				{
					"id":"tower_cake_14_2",
					"name":"魔塔14层-精英",
					"level_file":"tower/tower-14-2.json",
					"hard_level_file":"tower/tower-14-2_hard.json",
					"level_sprite":spr_matcha_manor_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_14_1",
					"rewards":[
						{"card_id":"whisky_bomb","target_shape":1},
						{"card_id":"aquarius_elve","target_shape":1}
					]
				},
				{
					"id":"tower_cake_15_1",
					"name":"魔塔15层-先锋",
					"level_file":"tower/tower-15-1.json",
					"hard_level_file":"tower/tower-15-1_hard.json",
					"level_sprite":spr_macchiato_port,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_14_2",
					"rewards":[
						{"card_id":"ice_bucket_bomb","target_shape":1},
						{"card_id":"king_long_bao","target_shape":1}
					]
				},
				{
					"id":"tower_cake_15_2",
					"name":"魔塔15层-精英",
					"level_file":"tower/tower-15-2.json",
					"hard_level_file":"tower/tower-15-2_hard.json",
					"level_sprite":spr_macchiato_port,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_15_1",
					"rewards":[
						{"card_id":"kettle_bomb","target_shape":1},
						{"card_id":"king_triple_long_bao","target_shape":1}
					]
				},
				{
					"id":"tower_cake_16_1",
					"name":"魔塔16层-先锋",
					"level_file":"tower/tower-16-1.json",
					"hard_level_file":"tower/tower-16-1_hard.json",
					"level_sprite":spr_cotton_candy_sky_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_15_2",
					"rewards":[
						{"card_id":"pineapple_explosive_bread","target_shape":1},
						{"card_id":"iron_fishbone","target_shape":2}
					]
				},
				{
					"id":"tower_cake_16_2",
					"name":"魔塔16层-精英",
					"level_file":"tower/tower-16-2.json",
					"hard_level_file":"tower/tower-16-2_hard.json",
					"level_sprite":spr_cotton_candy_sky_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_16_1",
					"rewards":[
						{"card_id":"ice_cream","target_shape":1}
					]
				},
				{
					"id":"tower_cake_17_1",
					"name":"魔塔17层-先锋",
					"level_file":"tower/tower-17-1.json",
					"hard_level_file":"tower/tower-17-1_hard.json",
					"level_sprite":spr_cotton_candy_sky_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_16_2",
					"rewards":[
						{"card_id":"lightning_baguette","target_shape":1}
					]
				},
				{
					"id":"tower_cake_17_2",
					"name":"魔塔17层-精英",
					"level_file":"tower/tower-17-2.json",
					"hard_level_file":"tower/tower-17-2_hard.json",
					"level_sprite":spr_cotton_candy_sky_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_17_1",
					"rewards":[
						{"card_id":"coffee_grounds","target_shape":2},
						{"card_id":"chili_powder","target_shape":1}
					]
				},
				{
					"id":"tower_cake_18_1",
					"name":"魔塔18层-先锋",
					"level_file":"tower/tower-18-1.json",
					"hard_level_file":"tower/tower-18-1_hard.json",
					"level_sprite":spr_jam_tribe_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_17_2",
					"rewards":[
						{"card_id":"wooden_plate","target_shape":2},
						{"card_id":"coffee_cup","target_shape":2}
					]
				},
				{
					"id":"tower_cake_18_2",
					"name":"魔塔18层-精英",
					"level_file":"tower/tower-18-2.json",
					"hard_level_file":"tower/tower-18-2_hard.json",
					"level_sprite":spr_jam_tribe_night,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_18_1",
					"rewards":[
						{"card_id":"mouse_clip","target_shape":2},
						{"card_id":"bull_firework","target_shape":1}
					]
				},
				{
					"id":"tower_cake_19_1",
					"name":"魔塔19层-先锋",
					"level_file":"tower/tower-19-1.json",
					"hard_level_file":"tower/tower-19-1_hard.json",
					"level_sprite":spr_jam_tribe_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_18_2",
					"rewards":[
						{"card_id":"coffee_pot","target_shape":2},
						{"card_id":"oden_pot","target_shape":2}
					]
				},
				{
					"id":"tower_cake_19_2",
					"name":"魔塔19层-精英",
					"level_file":"tower/tower-19-2.json",
					"hard_level_file":"tower/tower-19-2_hard.json",
					"level_sprite":spr_jam_tribe_daytime,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_19_1",
					"rewards":[
						{"card_id":"melon_shield","target_shape":2}
					]
				},
				{
					"id":"tower_cake_20_1",
					"name":"魔塔20层-先锋",
					"level_file":"tower/tower-20-1.json",
					"hard_level_file":"tower/tower-20-1_hard.json",
					"level_sprite":spr_snowcap_volcano,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_19_2",
					"rewards":[
						{"card_id":"ice_egg_boiler_pult","target_shape":2}
					]
				},
				{
					"id":"tower_cake_20_2",
					"name":"魔塔20层-精英",
					"level_file":"tower/tower-20-2.json",
					"hard_level_file":"tower/tower-20-2_hard.json",
					"level_sprite":spr_snowcap_volcano,
					"pre_music":mus_volcanic_tower_pre,
					"elite_music":mus_volcanic_tower_elite,
					"boss_music":mus_volcanic_tower_boss,
					"pre_level":"tower_cake_20_1",
					"rewards":[
						{"card_id":"large_fire","target_shape":2},
						{"card_id":"tang_hu_lu","target_shape":1}
					]
				},
				{
					"id":"tower_cake_21_1",
					"name":"魔塔21层-先锋",
					"level_file":"tower/tower-21-1.json",
					"hard_level_file":"tower/tower-21-1_hard.json",
					"level_sprite":spr_fennel_raft_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_20_2",
					"rewards":[
						{"card_id":"takoyaki","target_shape":2}
					]
				},
				{
					"id":"tower_cake_21_2",
					"name":"魔塔21层-精英",
					"level_file":"tower/tower-21-2.json",
					"hard_level_file":"tower/tower-21-2_hard.json",
					"level_sprite":spr_fennel_raft_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_21_1",
					"rewards":[
						{"card_id":"aquarius_elve","target_shape":2}
					]
				},
				{
					"id":"tower_cake_22_1",
					"name":"魔塔22层-先锋",
					"level_file":"tower/tower-22-1.json",
					"hard_level_file":"tower/tower-22-1_hard.json",
					"level_sprite":spr_fennel_raft_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_21_2",
					"rewards":[
						{"card_id":"chocolate_pult","target_shape":2}
					]
				},
				{
					"id":"tower_cake_22_2",
					"name":"魔塔22层-精英",
					"level_file":"tower/tower-22-2.json",
					"hard_level_file":"tower/tower-22-2_hard.json",
					"level_sprite":spr_fennel_raft_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_22_1",
					"rewards":[
						{"card_id":"salad_pult","target_shape":2},
						{"card_id":"flour_sack","target_shape":2}
					]
				},
				{
					"id":"tower_cake_23_1",
					"name":"魔塔23层-先锋",
					"level_file":"tower/tower-23-1.json",
					"hard_level_file":"tower/tower-23-1_hard.json",
					"level_sprite":spr_cumin_bridge_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_22_2",
					"rewards":[
						{"card_id":"hotdog_cannon","target_shape":2}
					]
				},
				{
					"id":"tower_cake_23_2",
					"name":"魔塔23层-精英",
					"level_file":"tower/tower-23-2.json",
					"hard_level_file":"tower/tower-23-2_hard.json",
					"level_sprite":spr_cumin_bridge_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_23_1",
					"rewards":[
						{"card_id":"stinky_tofu_pult","target_shape":2}
					]
				},
				{
					"id":"tower_cake_24_1",
					"name":"魔塔24层-先锋",
					"level_file":"tower/tower-24-1.json",
					"hard_level_file":"tower/tower-24-1_hard.json",
					"level_sprite":spr_cumin_bridge_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_23_2",
					"rewards":[
						{"card_id":"king_long_bao","target_shape":2}
					]
				},
				{
					"id":"tower_cake_24_2",
					"name":"魔塔24层-精英",
					"level_file":"tower/tower-24-2.json",
					"hard_level_file":"tower/tower-24-2_hard.json",
					"level_sprite":spr_cumin_bridge_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_24_1",
					"rewards":[
						{"card_id":"goblet_lamp","target_shape":2},
						{"card_id":"egg_boiler_pult","target_shape":2}
					]
				},
				{
					"id":"tower_cake_25_1",
					"name":"魔塔25层-先锋",
					"level_file":"tower/tower-25-1.json",
					"hard_level_file":"tower/tower-25-1_hard.json",
					"level_sprite":spr_marinade_garden,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_24_2",
					"rewards":[
						{"card_id":"xinjiang_fried_noodles","target_shape":2},
						{"card_id":"firework_dragon","target_shape":2}
					]
				},
				{
					"id":"tower_cake_25_2",
					"name":"魔塔25层-精英",
					"level_file":"tower/tower-25-2.json",
					"hard_level_file":"tower/tower-25-2_hard.json",
					"level_sprite":spr_marinade_garden,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_25_1",
					"rewards":[
						{"card_id":"cotton_candy","target_shape":2},
						{"card_id":"small_fire","target_shape":2}
					]
				},
				{
					"id":"tower_cake_26_1",
					"name":"魔塔26层-先锋",
					"level_file":"tower/tower-26-1.json",
					"hard_level_file":"tower/tower-26-1_hard.json",
					"level_sprite":spr_laurel_sky_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_25_2",
					"rewards":[
						{"card_id":"double_water_pipe","target_shape":2},
					]
				},
				{
					"id":"tower_cake_26_2",
					"name":"魔塔26层-精英",
					"level_file":"tower/tower-26-2.json",
					"hard_level_file":"tower/tower-26-2_hard.json",
					"level_sprite":spr_laurel_sky_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_26_1",
					"rewards":[
						{"card_id":"coke_bomb","target_shape":2},
						{"card_id":"pineapple_explosive_bread","target_shape":2}
					]
				},
				{
					"id":"tower_cake_27_1",
					"name":"魔塔27层-先锋",
					"level_file":"tower/tower-27-1.json",
					"hard_level_file":"tower/tower-27-1_hard.json",
					"level_sprite":spr_laurel_sky_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_26_2",
					"rewards":[
						{"card_id":"triple_wine_rack","target_shape":2}
					]
				},
				{
					"id":"tower_cake_27_2",
					"name":"魔塔27层-精英",
					"level_file":"tower/tower-27-2.json",
					"hard_level_file":"tower/tower-27-2_hard.json",
					"level_sprite":spr_laurel_sky_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_27_1",
					"rewards":[
						{"card_id":"wine_bottle_bomb","target_shape":2}
					]
				},
				{
					"id":"tower_cake_28_1",
					"name":"魔塔28层-先锋",
					"level_file":"tower/tower-28-1.json",
					"hard_level_file":"tower/tower-28-1_hard.json",
					"level_sprite":spr_bayleaf_airport_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_27_2",
					"rewards":[
						{"card_id":"gatlin_long_bao","target_shape":2}
					]
				},
				{
					"id":"tower_cake_28_2",
					"name":"魔塔28层-精英",
					"level_file":"tower/tower-28-2.json",
					"hard_level_file":"tower/tower-28-2_hard.json",
					"level_sprite":spr_bayleaf_airport_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"pre_level":"tower_cake_28_1",
					"rewards":[
						{"card_id":"kettle_bomb","target_shape":2},
						{"card_id":"chili_powder","target_shape":2}
					]
				},
				{
					"id":"tower_cake_29_1",
					"name":"魔塔29层-先锋",
					"level_file":"tower/tower-29-1.json",
					"hard_level_file":"tower/tower-29-1_hard.json",
					"level_sprite":spr_bayleaf_airport_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_28_2",
					"rewards":[
						{"card_id":"king_triple_long_bao","target_shape":2},
						{"card_id":"tar_sprayer","target_shape":2}
					]
				},
				{
					"id":"tower_cake_29_2",
					"name":"魔塔29层-精英",
					"level_file":"tower/tower-29-2.json",
					"hard_level_file":"tower/tower-29-2_hard.json",
					"level_sprite":spr_bayleaf_airport_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_29_1",
					"rewards":[
						{"card_id":"ice_cream","target_shape":2},
						{"card_id":"hamburger","target_shape":2}
					]
				},
				{
					"id":"tower_cake_30_1",
					"name":"魔塔30层-先锋",
					"level_file":"tower/tower-30-1.json",
					"hard_level_file":"tower/tower-30-1_hard.json",
					"level_sprite":spr_spice_airship,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_29_2",
					"rewards":[
						{"card_id":"lightning_baguette","target_shape":2},
						{"card_id":"rotating_coffee_pot","target_shape":2}
					]
				},
				{
					"id":"tower_cake_30_2",
					"name":"魔塔30层-精英",
					"level_file":"tower/tower-30-2.json",
					"hard_level_file":"tower/tower-30-2_hard.json",
					"level_sprite":spr_spice_airship,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_night_boss,
					"pre_level":"tower_cake_30_1",
					"rewards":[
						{"card_id":"ventilation_fan","target_shape":2},
						{"card_id":"tang_hu_lu","target_shape":2}
					]
				},
			]
		}
	)
	
	register_map(
		"volcanic_island",
		{
			"map_name":"火山岛",
			"map_sprite":spr_volcanic_island,
			"levels_data":[
				{
					"id":"mustard_cottage_daytime",
					"name":"芥末小屋（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":0,
					"button_x":1415,
					"button_y":455,
					"level_file":"volcanic/mustard_cottage_daytime.json",
					"hard_level_file":"volcanic/mustard_cottage_daytime_hard.json",
					"level_sprite":spr_mustard_cottage_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":21,
					"pre_level_require":[]
				},
				{
					"id":"mustard_cottage_night",
					"name":"芥末小屋（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":1,
					"button_x":1290,
					"button_y":540,
					"level_file":"volcanic/mustard_cottage_night.json",
					"hard_level_file":"volcanic/mustard_cottage_night_hard.json",
					"level_sprite":spr_mustard_cottage_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":22,
					"pre_level_require":[]
				},
				{
					"id":"mint_beach_daytime",
					"name":"薄荷海滩（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":2,
					"button_x":1390,
					"button_y":650,
					"level_file":"volcanic/mint_beach_daytime.json",
					"hard_level_file":"volcanic/mint_beach_daytime_hard.json",
					"level_sprite":spr_mint_beach_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":23,
					"pre_level_require":[]
				},
				{
					"id":"mint_beach_night",
					"name":"薄荷海滩（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":3,
					"button_x":1260,
					"button_y":743,
					"level_file":"volcanic/mint_beach_night.json",
					"hard_level_file":"volcanic/mint_beach_night_hard.json",
					"level_sprite":spr_mint_beach_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":24,
					"pre_level_require":[]
				},
				{
					"id":"cheese_castle",
					"name":"芝士城堡",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":4,
					"button_x":1070,
					"button_y":755,
					"level_file":"volcanic/cheese_castle.json",
					"hard_level_file":"volcanic/cheese_castle_hard.json",
					"level_sprite":spr_cheese_castle,
					"pre_music":mus_volcanic_island_crown_pre,
					"elite_music":mus_volcanic_island_crown_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":25,
					"pre_level_require":[]
				},
				{
					"id":"tower_cake",
					"name":"魔塔蛋糕",
					"button_spr":spr_levelselect_button,
					"button_index":14,
					"button_x":1120,
					"button_y":125,
					"level_file":"volcanic/cheese_castle.json",
					"hard_level_file":"volcanic/cheese_castle_hard.json",
					"level_sprite":spr_cheese_castle,
					"pre_music":mus_volcanic_island_crown_pre,
					"elite_music":mus_volcanic_island_crown_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":8,
					"pre_level_require":[]
				},
				{
					"id":"charcoal_jungle_daytime",
					"name":"炭烧雨林（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":5,
					"button_x":758,
					"button_y":730,
					"level_file":"volcanic/charcoal_jungle_daytime.json",
					"hard_level_file":"volcanic/charcoal_jungle_daytime_hard.json",
					"level_sprite":spr_charcoal_jungle_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":26,
					"pre_level_require":[]
				},
				{
					"id":"charcoal_jungle_night",
					"name":"炭烧雨林（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":6,
					"button_x":628,
					"button_y":680,
					"level_file":"volcanic/charcoal_jungle_night.json",
					"hard_level_file":"volcanic/charcoal_jungle_night_hard.json",
					"level_sprite":spr_charcoal_jungle_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":27,
					"pre_level_require":[]
				},
				{
					"id":"matcha_manor_daytime",
					"name":"抹茶庄园（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":7,
					"button_x":518,
					"button_y":475,
					"level_file":"volcanic/matcha_manor_daytime.json",
					"hard_level_file":"volcanic/matcha_manor_daytime_hard.json",
					"level_sprite":spr_matcha_manor_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":28,
					"pre_level_require":[]
				},
				{
					"id":"matcha_manor_night",
					"name":"抹茶庄园（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":8,
					"button_x":640,
					"button_y":440,
					"level_file":"volcanic/matcha_manor_night.json",
					"hard_level_file":"volcanic/matcha_manor_night_hard.json",
					"level_sprite":spr_matcha_manor_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":29,
					"pre_level_require":[]
				},
				{
					"id":"macchiato_port",
					"name":"玛奇朵港",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":9,
					"button_x":957,
					"button_y":330,
					"level_file":"volcanic/macchiato_port.json",
					"hard_level_file":"volcanic/macchiato_port_hard.json",
					"level_sprite":spr_macchiato_port,
					"pre_music":mus_volcanic_island_crown_pre,
					"elite_music":mus_volcanic_island_crown_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":30,
					"pre_level_require":[]
				},
				{
					"id":"cotton_candy_sky_daytime",
					"name":"棉花糖天空（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":10,
					"button_x":800,
					"button_y":300,
					"level_file":"volcanic/cotton_candy_sky_daytime.json",
					"hard_level_file":"volcanic/cotton_candy_sky_daytime_hard.json",
					"level_sprite":spr_cotton_candy_sky_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":31,
					"pre_level_require":[]
				},
				{
					"id":"cotton_candy_sky_night",
					"name":"棉花糖天空（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":11,
					"button_x":657,
					"button_y":290,
					"level_file":"volcanic/cotton_candy_sky_night.json",
					"hard_level_file":"volcanic/cotton_candy_sky_night_hard.json",
					"level_sprite":spr_cotton_candy_sky_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":32,
					"pre_level_require":[]
				},
				{
					"id":"jam_tribe_daytime",
					"name":"果酱部落（日）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":12,
					"button_x":495,
					"button_y":230,
					"level_file":"volcanic/jam_tribe_daytime.json",
					"hard_level_file":"volcanic/jam_tribe_daytime_hard.json",
					"level_sprite":spr_jam_tribe_daytime,
					"pre_music":mus_volcanic_island_daytime_pre,
					"elite_music":mus_volcanic_island_daytime_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":33,
					"pre_level_require":[]
				},
				{
					"id":"jam_tribe_night",
					"name":"果酱部落（夜）",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":13,
					"button_x":580,
					"button_y":180,
					"level_file":"volcanic/jam_tribe_night.json",
					"hard_level_file":"volcanic/jam_tribe_night_hard.json",
					"level_sprite":spr_jam_tribe_night,
					"pre_music":mus_volcanic_island_night_pre,
					"elite_music":mus_volcanic_island_night_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":34,
					"pre_level_require":[]
				},
				{
					"id":"snowcap_volcano",
					"name":"雪顶火山",
					"button_spr":spr_levelselect_button_volcanic,
					"button_index":14,
					"button_x":730,
					"button_y":118,
					"level_file":"volcanic/snowcap_volcano.json",
					"hard_level_file":"volcanic/snowcap_volcano_hard.json",
					"level_sprite":spr_snowcap_volcano,
					"pre_music":mus_volcanic_island_crown_pre,
					"elite_music":mus_volcanic_island_crown_elite,
					"boss_music":mus_volcanic_island_daytime_boss,
					"player_level_require":35,
					"pre_level_require":[]
				},
																										
			]
		}
	)
	register_map(
		"floating_island",
		{
			"map_name":"浮空岛",
			"map_sprite":spr_floating_island,
			"levels_data":[
				{
					"id":"fennel_raft_daytime",
					"name":"茴香竹筏（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":0,
					"button_x":900,
					"button_y":790,
					"level_file":"floating/fennel_raft_daytime.json",
					"hard_level_file":"floating/fennel_raft_daytime_hard.json",
					"level_sprite":spr_fennel_raft_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":41,
					"pre_level_require":[]
				},					
				{
					"id":"fennel_raft_night",
					"name":"茴香竹筏（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":1,
					"button_x":1100,
					"button_y":760,
					"level_file":"floating/fennel_raft_night.json",
					"hard_level_file":"floating/fennel_raft_night_hard.json",
					"level_sprite":spr_fennel_raft_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":42,
					"pre_level_require":[]
				},							
				{
					"id":"cumin_bridge_daytime",
					"name":"孜然断桥（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":2,
					"button_x":1420,
					"button_y":600,
					"level_file":"floating/cumin_bridge_daytime.json",
					"hard_level_file":"floating/cumin_bridge_daytime_hard.json",
					"level_sprite":spr_cumin_bridge_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":43,
					"pre_level_require":[]
				},			
				{
					"id":"cumin_bridge_night",
					"name":"孜然断桥（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":3,
					"button_x":1250,
					"button_y":590,
					"level_file":"floating/cumin_bridge_night.json",
					"hard_level_file":"floating/cumin_bridge_night_hard.json",
					"level_sprite":spr_cumin_bridge_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":44,
					"pre_level_require":[]
				},
				{
					"id":"marinade_garden",
					"name":"卤料花园",
					"button_spr":spr_levelselect_button_floating,
					"button_index":4,
					"button_x":1030,
					"button_y":520,
					"level_file":"floating/marinade_garden.json",
					"hard_level_file":"floating/marinade_garden_hard.json",
					"level_sprite":spr_marinade_garden,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":45,
					"pre_level_require":[]
				},
				{
					"id":"laurel_sky_daytime",
					"name":"月桂天空（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":5,
					"button_x":840,
					"button_y":510,
					"level_file":"floating/laurel_sky_daytime.json",
					"hard_level_file":"floating/laurel_sky_daytime_hard.json",
					"level_sprite":spr_laurel_sky_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":46,
					"pre_level_require":[]
				},
				{
					"id":"laurel_sky_night",
					"name":"月桂天空（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":6,
					"button_x":700,
					"button_y":490,
					"level_file":"floating/laurel_sky_night.json",
					"hard_level_file":"floating/laurel_sky_night_hard.json",
					"level_sprite":spr_laurel_sky_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":47,
					"pre_level_require":[]
				},
				{
					"id":"bayleaf_airport_daytime",
					"name":"香叶空港（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":7,
					"button_x":560,
					"button_y":450,
					"level_file":"floating/bayleaf_airport_daytime.json",
					"hard_level_file":"floating/bayleaf_airport_daytime_hard.json",
					"level_sprite":spr_bayleaf_airport_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":48,
					"pre_level_require":[]
				},
				{
					"id":"bayleaf_airport_night",
					"name":"香叶空港（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":8,
					"button_x":400,
					"button_y":380,
					"level_file":"floating/bayleaf_airport_night.json",
					"hard_level_file":"floating/bayleaf_airport_night_hard.json",
					"level_sprite":spr_bayleaf_airport_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":49,
					"pre_level_require":[]
				},
				{
					"id":"spice_airship",
					"name":"香料飞船",
					"button_spr":spr_levelselect_button_floating,
					"button_index":9,
					"button_x":270,
					"button_y":300,
					"level_file":"floating/spice_airship.json",
					"hard_level_file":"floating/spice_airship_hard.json",
					"level_sprite":spr_spice_airship,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":50,
					"pre_level_require":[]
				},
				{
					"id":"pepper_floating_isle_daytime",
					"name":"花椒浮岛（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":10,
					"button_x":460,
					"button_y":230,
					"level_file":"floating/pepper_floating_isle_daytime.json",
					"hard_level_file":"floating/pepper_floating_isle_daytime_hard.json",
					"level_sprite":spr_pepper_floating_isle_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":99,
					"pre_level_require":[]
				},
				{
					"id":"pepper_floating_isle_night",
					"name":"花椒浮岛（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":11,
					"button_x":660,
					"button_y":310,
					"level_file":"floating/pepper_floating_isle_night.json",
					"hard_level_file":"floating/pepper_floating_isle_night_hard.json",
					"level_sprite":spr_pepper_floating_isle_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":99,
					"pre_level_require":[]
				},
				{
					"id":"lilac_rainbow_daytime",
					"name":"丁香彩虹（日）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":12,
					"button_x":1080,
					"button_y":280,
					"level_file":"floating/lilac_rainbow_daytime.json",
					"hard_level_file":"floating/lilac_rainbow_daytime_hard.json",
					"level_sprite":spr_lilac_rainbow_daytime,
					"pre_music":mus_floating_island_daytime_pre,
					"elite_music":mus_floating_island_daytime_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":99,
					"pre_level_require":[]
				},
				{
					"id":"lilac_rainbow_night",
					"name":"丁香彩虹（夜）",
					"button_spr":spr_levelselect_button_floating,
					"button_index":13,
					"button_x":970,
					"button_y":340,
					"level_file":"floating/lilac_rainbow_night.json",
					"hard_level_file":"floating/lilac_rainbow_night_hard.json",
					"level_sprite":spr_lilac_rainbow_night,
					"pre_music":mus_floating_island_night_pre,
					"elite_music":mus_floating_island_night_elite,
					"boss_music":mus_floating_island_night_boss,
					"player_level_require":99,
					"pre_level_require":[]
				},
				{
					"id":"spices_central_isle",
					"name":"十三香中心岛",
					"button_spr":spr_levelselect_button_floating,
					"button_index":14,
					"button_x":965,
					"button_y":160,
					"level_file":"floating/spices_central_isle.json",
					"hard_level_file":"floating/spices_central_isle_hard.json",
					"level_sprite":spr_spices_central_isle,
					"pre_music":mus_floating_island_crown_pre,
					"elite_music":mus_floating_island_crown_elite,
					"boss_music":mus_floating_island_daytime_boss,
					"player_level_require":99,
					"pre_level_require":[]
				},
				{
					"id":"tower_cake",
					"name":"魔塔蛋糕",
					"button_spr":spr_levelselect_button,
					"button_index":14,
					"button_x":1228,
					"button_y":330,
					"level_file":"volcanic/cheese_castle.json",
					"hard_level_file":"volcanic/cheese_castle_hard.json",
					"level_sprite":spr_cheese_castle,
					"pre_music":mus_volcanic_island_crown_pre,
					"elite_music":mus_volcanic_island_crown_elite,
					"boss_music":mus_volcanic_island_night_boss,
					"player_level_require":8,
					"pre_level_require":[]
				},
			]
		}
	)
}