function gods_shop_init(){
    register_gods_goods("apollo",  {"type":"card","cost":"30","unlock_item_id":"apollo",  "description":"阿波罗神使：生产巨量火苗",  "display_name":"阿波罗神使"})
    register_gods_goods("ares",    {"type":"card","cost":"30","unlock_item_id":"ares",    "description":"阿瑞斯神使：向前后发射威力巨大的子弹",  "display_name":"阿瑞斯神使"})
    register_gods_goods("cupid",   {"type":"card","cost":"30","unlock_item_id":"cupid",   "description":"丘比特神使：向前方三行发射威力巨大的箭矢",  "display_name":"丘比特神使"})
    register_gods_goods("diana",   {"type":"card","cost":"30","unlock_item_id":"diana",   "description":"戴安娜神使：发射大量全屏追踪的飞镖",  "display_name":"戴安娜神使"})
    register_gods_goods("thor",    {"type":"card","cost":"30","unlock_item_id":"thor",    "description":"索尔神使：投掷出威力巨大的冰锤",    "display_name":"索尔神使"})
    register_gods_goods("poseidon",{"type":"card","cost":"30","unlock_item_id":"poseidon","description":"波塞冬神使：发射5*5范围穿透的水波",  "display_name":"波塞冬神使"})
    register_gods_goods("loki",    {"type":"card","cost":"30","unlock_item_id":"loki",    "description":"洛基神使：巨额增加穿过子弹的伤害",    "display_name":"洛基神使"})
    register_gods_goods("hera",    {"type":"card","cost":"30","unlock_item_id":"hera",    "description":"赫拉神使：保护被罩住的卡片，摧毁时爆炸",    "display_name":"赫拉神使"})
    register_gods_goods("odin",    {"type":"card","cost":"45","unlock_item_id":"odin",    "description":"奥丁神使：发射直线穿透，威力巨大的长矛",    "display_name":"奥丁神使"})
	register_gods_goods("aurora",    {"type":"card","cost":"45","unlock_item_id":"aurora",    "description":"欧若拉神使：为本行投掷类卡片增伤",    "display_name":"欧若拉神使"})
	register_gods_goods("brahma",    {"type":"card","cost":"60","unlock_item_id":"brahma",    "description":"梵天神使：变身出多个上一次种下的卡片",    "display_name":"梵天神使"})

    register_gods_goods("apollo_1",  {"type":"shape","cost":"45","unlock_item_id":"apollo",  "target_shape":1,"description":"阿波罗圣神：生产巨量火苗",    "display_name":"太阳神三转凭证",    "spr":spr_c_apollo_1})
    register_gods_goods("ares_1",    {"type":"shape","cost":"45","unlock_item_id":"ares",    "target_shape":1,"description":"阿瑞斯圣神：向前后发射威力巨大的子弹",    "display_name":"战神三转凭证",      "spr":spr_c_ares_1})
    register_gods_goods("cupid_1",   {"type":"shape","cost":"45","unlock_item_id":"cupid",   "target_shape":1,"description":"丘比特圣神：向前方三行发射威力巨大的箭矢",    "display_name":"爱神三转凭证",      "spr":spr_c_cupid_1})
    register_gods_goods("diana_1",   {"type":"shape","cost":"45","unlock_item_id":"diana",   "target_shape":1,"description":"戴安娜圣神：发射大量全屏追踪的飞镖",    "display_name":"月神三转凭证",      "spr":spr_c_diana_1})
    register_gods_goods("thor_1",    {"type":"shape","cost":"45","unlock_item_id":"thor",    "target_shape":1,"description":"索尔圣神：投掷出威力巨大的冰锤",      "display_name":"雷神三转凭证",      "spr":spr_c_thor_1})
    register_gods_goods("poseidon_1",{"type":"shape","cost":"45","unlock_item_id":"poseidon","target_shape":1,"description":"波塞冬圣神：发射5*5范围穿透的水波",    "display_name":"海神三转凭证",      "spr":spr_c_poseidon_1})
    register_gods_goods("loki_1",    {"type":"shape","cost":"45","unlock_item_id":"loki",    "target_shape":1,"description":"洛基圣神：巨额增加穿过子弹的伤害",      "display_name":"火神三转凭证",      "spr":spr_c_loki_1})
    register_gods_goods("hera_1",    {"type":"shape","cost":"45","unlock_item_id":"hera",    "target_shape":1,"description":"赫拉圣神：保护被罩住的卡片，摧毁时爆炸",      "display_name":"天后三转凭证",      "spr":spr_c_hera_1})
    register_gods_goods("odin_1",    {"type":"shape","cost":"60","unlock_item_id":"odin",    "target_shape":1,"description":"奥丁圣神：发射直线穿透，威力巨大的长矛",      "display_name":"主神三转凭证",      "spr":spr_c_odin_1})
	register_gods_goods("aurora_1",    {"type":"shape","cost":"60","unlock_item_id":"aurora",    "target_shape":1,"description":"欧若拉圣神：为本行投掷类卡片增伤，死亡后爆炸",      "display_name":"曙光女神三转凭证",      "spr":spr_c_aurora_1})
	register_gods_goods("brahma_1",    {"type":"shape","cost":"90","unlock_item_id":"brahma",    "target_shape":1,"description":"梵天圣神：变身出多个上一次种下的卡片",      "display_name":"创造神三转凭证",      "spr":spr_c_brahma_1})


    register_gods_goods("apollo_2",  {"type":"shape","cost":"60","unlock_item_id":"apollo",  "target_shape":2,"description":"太阳神·阿波罗：生产巨量火苗",    "display_name":"太阳神四转凭证",    "spr":spr_c_apollo_2})
    register_gods_goods("ares_2",    {"type":"shape","cost":"60","unlock_item_id":"ares",    "target_shape":2,"description":"战神·阿瑞斯：向前后发射威力巨大的子弹",      "display_name":"战神四转凭证",      "spr":spr_c_ares_2})
    register_gods_goods("cupid_2",   {"type":"shape","cost":"60","unlock_item_id":"cupid",   "target_shape":2,"description":"爱神·丘比特：向前方三行发射威力巨大的箭矢",      "display_name":"爱神四转凭证",      "spr":spr_c_cupid_2})
    register_gods_goods("diana_2",   {"type":"shape","cost":"60","unlock_item_id":"diana",   "target_shape":2,"description":"月神·戴安娜：发射大量全屏追踪的飞镖",      "display_name":"月神四转凭证",      "spr":spr_c_diana_2})
    register_gods_goods("thor_2",    {"type":"shape","cost":"60","unlock_item_id":"thor",    "target_shape":2,"description":"雷神·索尔：投掷出威力巨大的冰锤",        "display_name":"雷神四转凭证",      "spr":spr_c_thor_2})
    register_gods_goods("poseidon_2",{"type":"shape","cost":"60","unlock_item_id":"poseidon","target_shape":2,"description":"海神·波塞冬：发射5*5范围穿透的水波",      "display_name":"海神四转凭证",      "spr":spr_c_poseidon_2})
    register_gods_goods("loki_2",    {"type":"shape","cost":"60","unlock_item_id":"loki",    "target_shape":2,"description":"火神·洛基：巨额增加穿过子弹的伤害",	   "display_name":"火神四转凭证",      "spr":spr_c_loki_2})
    register_gods_goods("hera_2",    {"type":"shape","cost":"60","unlock_item_id":"hera",    "target_shape":2,"description":"天后·赫拉：保护被罩住的卡片，摧毁时爆炸",        "display_name":"天后四转凭证",      "spr":spr_c_hera_2})
    register_gods_goods("odin_2",    {"type":"shape","cost":"90","unlock_item_id":"odin",    "target_shape":2,"description":"主神·奥丁：发射直线穿透，威力巨大长矛",      "display_name":"主神四转凭证",      "spr":spr_c_odin_2})
	register_gods_goods("aurora_2",    {"type":"shape","cost":"90","unlock_item_id":"aurora",    "target_shape":2,"description":"曙光女神·欧若拉：为本行投掷类卡片增伤，死亡后爆炸",      "display_name":"曙光女神四转凭证",      "spr":spr_c_aurora_2})
	register_gods_goods("brahma_2",    {"type":"shape","cost":"120","unlock_item_id":"brahma",    "target_shape":2,"description":"创造神·梵天：变身出多个上一次种下的卡片",      "display_name":"创造神四转凭证",      "spr":spr_c_brahma_2})

    register_gods_goods("apollo_3",  {"type":"shape","cost":"120","unlock_item_id":"apollo",  "target_shape":3,"description":"至尊太阳神：生产巨量火苗",      "display_name":"太阳神终转凭证",    "spr":spr_c_apollo_3})
    register_gods_goods("ares_3",    {"type":"shape","cost":"120","unlock_item_id":"ares",    "target_shape":3,"description":"至尊战神：向前后发射威力巨大的子弹",        "display_name":"战神终转凭证",      "spr":spr_c_ares_3})
    register_gods_goods("cupid_3",   {"type":"shape","cost":"120","unlock_item_id":"cupid",   "target_shape":3,"description":"至尊爱神：向前方三行发射威力巨大的箭矢",        "display_name":"爱神终转凭证",      "spr":spr_c_cupid_3})
    register_gods_goods("diana_3",   {"type":"shape","cost":"120","unlock_item_id":"diana",   "target_shape":3,"description":"至尊月神：发射大量全屏追踪的飞镖",        "display_name":"月神终转凭证",      "spr":spr_c_diana_3})
    register_gods_goods("thor_3",    {"type":"shape","cost":"120","unlock_item_id":"thor",    "target_shape":3,"description":"至尊雷神：投掷出威力巨大的冰锤",        "display_name":"雷神终转凭证",      "spr":spr_c_thor_3})
    register_gods_goods("poseidon_3",{"type":"shape","cost":"120","unlock_item_id":"poseidon","target_shape":3,"description":"至尊海神：发射7*5范围穿透的水波",        "display_name":"海神终转凭证",      "spr":spr_c_poseidon_3})
    register_gods_goods("loki_3",    {"type":"shape","cost":"120","unlock_item_id":"loki",    "target_shape":3,"description":"至尊火神：巨额增加穿过子弹的伤害",	   "display_name":"火神终转凭证",      "spr":spr_c_loki_3})
    register_gods_goods("hera_3",    {"type":"shape","cost":"120","unlock_item_id":"hera",    "target_shape":3,"description":"至尊天后：保护被罩住的卡片，摧毁时爆炸",        "display_name":"天后终转凭证",      "spr":spr_c_hera_3})
    register_gods_goods("odin_3",    {"type":"shape","cost":"180","unlock_item_id":"odin",    "target_shape":3,"description":"至尊主神：发射直线穿透，威力巨大的长矛",      "display_name":"主神终转凭证",      "spr":spr_c_odin_3})
	register_gods_goods("aurora_3",    {"type":"shape","cost":"180","unlock_item_id":"aurora",    "target_shape":3,"description":"至尊曙光女神：为本行及相邻行投掷类卡片增伤，死亡后爆炸",      "display_name":"曙光女神终转凭证",      "spr":spr_c_aurora_3})
	register_gods_goods("brahma_3",    {"type":"shape","cost":"240","unlock_item_id":"brahma",    "target_shape":3,"description":"至尊创造神：变身出多个上一次种下的卡片",      "display_name":"创造神终转凭证",      "spr":spr_c_brahma_3})
	
	register_gods_goods("coal_starfish_real_1",   {"type":"shape","cost":"0","unlock_item_id":"coal_starfish_real",   "target_shape":1,"description":"海星大帝神力的一部分，为什么会出现在这里？",    "display_name":"芝士焗海星(真）",      "spr":spr_c_coal_starfish_real_1})
	register_gods_goods("coal_starfish_real_2",   {"type":"shape","cost":"0","unlock_item_id":"coal_starfish_real",   "target_shape":2,"description":"海星大帝神力的全部，为什么会出现在这里？",    "display_name":"芥末海星刺身（真）",      "spr":spr_c_coal_starfish_real_2})

	register_gods_goods("s_clover", {"type":"item","cost":"1","unlock_item_id":"clover_S","description":"S级四叶草：提升强化概率至3倍","display_name":"S级四叶草","spr":spr_craft_material,"spr_index":12})
	register_gods_goods("ss_clover", {"type":"item","cost":"2","unlock_item_id":"clover_SS","description":"SS四叶草：提升强化概率至3.3倍","display_name":"SS四叶草","spr":spr_craft_material,"spr_index":13})
	register_gods_goods("sss_clover", {"type":"item","cost":"4","unlock_item_id":"clover_SSS","description":"SSS四叶草：提升强化概率至3.6倍","display_name":"SSS四叶草","spr":spr_craft_material,"spr_index":14})
	register_gods_goods("sssr_clover", {"type":"item","cost":"8","unlock_item_id":"clover_SSR","description":"SSR四叶草：提升强化概率至4倍","display_name":"SSR四叶草","spr":spr_craft_material,"spr_index":15})
}