var inst = instance_create_depth(x+40,y+50,depth-500,obj_takoyaki_bullet)
inst.damage = atk
inst.move_speed = 10
inst.target_enemy = noone
inst.banding_card_obj = id
inst.row = grid_row
inst.sprite_index = bullet_shape
inst.is_splash = (splash_ratio > 0)
inst.splash_ratio = splash_ratio
