instance_destroy(obj_gods_hall_closer)
instance_destroy(obj_gods_hall_wish)
instance_destroy(obj_gods_hall_bag)
instance_destroy(obj_gods_hall_reward)
instance_destroy(obj_gods_store_enter)
obj_player_info_ui.menu_type = 0
obj_world_map_button.world_map = 0