function cookbook_registry_init(){
	global.cookbook_pool = ds_map_create()
	global.cookbook_list = []
}

function register_cookbook(cookbook_id,cookbook_data){
	ds_map_add(global.cookbook_pool,cookbook_id,cookbook_data)
	array_push(global.cookbook_list,cookbook_id)
}

function get_cookbook_data(cookbook_id){
	return ds_map_find_value(global.cookbook_pool,cookbook_id)
}

function is_cookbook_equipped(cookbook_id){
	var cd = get_cookbook_data(cookbook_id)
	var cl = global.save_data.equipped_cookbook[cd.rank]
	if array_get_index(cl,cookbook_id) != -1{
		return true
	}
	return false
}

function equip_cookbook(cookbook_id){
	if !is_cookbook_equipped(cookbook_id){
		var cd = get_cookbook_data(cookbook_id)
		array_push(global.save_data.equipped_cookbook[cd.rank],cookbook_id)
	}
}

function unequip_cookbook(cookbook_id){
	if is_cookbook_equipped(cookbook_id){
		var cd = get_cookbook_data(cookbook_id)
		array_delete(global.save_data.equipped_cookbook[cd.rank],array_get_index(global.save_data.equipped_cookbook[cd.rank],cookbook_id),1)
	}
}

function cookbook_init(){
	cookbook_registry_init()
	register_cookbook(
		"nanxiang_bun",
		{
			"rank":0,
			"title":"南翔小笼包",
			"tiny_desc":"增加包子卡生命值",
			"desc":"所有包子类卡片生命值变为10倍",
			"icon":0,
			"modif":[
				{
					"card_id":["xiao_long_bao","double_long_bao","ice_long_bao","double_ice_long_bao","gatlin_long_bao","gatlin_ice_long_bao","triple_long_bao","triple_ice_long_bao","king_long_bao","king_triple_long_bao"],
					"modif_type":"hp",
					"modif_calc":"multiply",
					"amount":10
				}
			]
		}
	)
	register_cookbook(
		"coffee_milktea",
		{
			"rank":0,
			"title":"咖啡奶茶",
			"tiny_desc":"减少咖啡卡冷却",
			"desc":"除旋转咖啡喷壶外的咖啡类卡片冷却时间减少2秒",
			"icon":1,
			"modif":[
				{
					"card_id":["coffee_cup","water_tea_cup","coffee_pot"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"deluxe_combo",
		{
			"rank":0,
			"title":"美食豪华套餐",
			"tiny_desc":"减少汉堡包和可乐炸弹冷却",
			"desc":"汉堡包冷却时间减少1秒，生命值变为10倍\n可乐炸弹冷却时间减少1秒",
			"icon":2,
			"modif":[
				{
					"card_id":["hamburger","coke_bomb"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				},
				{
					"card_id":["hamburger"],
					"modif_type":"hp",
					"modif_calc":"multiply",
					"amount":10
				}
			]
		}
	)
	register_cookbook(
		"chilled_watermelon",
		{
			"rank":0,
			"title":"冰镇西瓜",
			"tiny_desc":"增加瓜皮护罩生命值",
			"desc":"瓜皮护罩生命值增加20%",
			"icon":3,
			"modif":[
				{
					"card_id":["melon_shield"],
					"modif_type":"hp",
					"modif_calc":"multiply",
					"amount":1.2
				}
			]
		}
	)
	register_cookbook(
		"spicy_hotpot",
		{
			"rank":0,
			"title":"麻辣烫",
			"tiny_desc":"减少火盆耗火",
			"desc":"火盆能量消耗降低25",
			"icon":4,
			"modif":[
				{
					"card_id":["brazier"],
					"modif_type":"cost",
					"modif_calc":"plus",
					"amount":-25
				}
			]
		}
	)
	register_cookbook(
		"portuguese_egg_tart",
		{
			"rank":0,
			"title":"葡式蛋挞",
			"tiny_desc":"减少煮蛋器投手冷却",
			"desc":"煮蛋器投手冷却时间减少1秒",
			"icon":5,
			"modif":[
				{
					"card_id":["egg_boiler_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"pineapple_pudding",
		{
			"rank":0,
			"title":"菠萝布丁",
			"tiny_desc":"加强樱桃反弹布丁",
			"desc":"樱桃反弹布丁获得反伤效果，且每秒回复10点生命\n值\n樱桃反弹布丁生命值变为2倍",
			"icon":6,
			"modif":[
				{
					"card_id":["cherry_pudding"],
					"modif_type":"hp",
					"modif_calc":"multiply",
					"amount":2
				}
			]
		}
	)
	register_cookbook(
		"wangfujin_bun",
		{
			"rank":1,
			"title":"王府井包子",
			"tiny_desc":"减少包子卡冷却",
			"desc":"除机枪小笼包外的包子类卡片冷却时间减少1秒",
			"icon":7,
			"modif":[
				{
					"card_id":["xiao_long_bao","double_long_bao","ice_long_bao","double_ice_long_bao","gatlin_ice_long_bao","triple_long_bao","triple_ice_long_bao"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"kopi_luwak",
		{
			"rank":1,
			"title":"猫屎咖啡",
			"tiny_desc":"减少旋转咖啡喷壶冷却",
			"desc":"旋转咖啡喷壶冷却时间减少5秒",
			"icon":8,
			"modif":[
				{
					"card_id":["rotating_coffee_pot"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				}
			]
		}
	)
	register_cookbook(
		"wine_chicken",
		{
			"rank":1,
			"title":"酒蒸鸡",
			"tiny_desc":"减少酒瓶炸弹冷却",
			"desc":"酒瓶炸弹冷却时间减少2秒",
			"icon":9,
			"modif":[
				{
					"card_id":["wine_bottle_bomb"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"popcorn_chicken",
		{
			"rank":1,
			"title":"劲爆鸡米花",
			"tiny_desc":"减少面粉袋冷却",
			"desc":"面粉袋冷却时间减少2秒",
			"icon":10,
			"modif":[
				{
					"card_id":["flour_sack"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"grape_wine",
		{
			"rank":1,
			"title":"葡萄美酒",
			"tiny_desc":"减少酒杯灯生长时间",
			"desc":"酒杯灯生长时间减少30秒",
			"icon":11,
			"modif":[
			]
		}
	)
	register_cookbook(
		"chocolate_snowball",
		{
			"rank":1,
			"title":"巧克力雪球",
			"tiny_desc":"加强巧克力大炮",
			"desc":"巧克力大炮冷却时间减少5秒，攻击间隔减少1秒\n巧克力投手冷却时间减少3秒",
			"icon":12,
			"modif":[
				{
					"card_id":["chocolate_cannon"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				},
				{
					"card_id":["chocolate_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-3*60
				},
				{
					"card_id":["chocolate_cannon"],
					"modif_type":"cycle",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"roast_turkey",
		{
			"rank":1,
			"title":"冷烤火鸡",
			"tiny_desc":"减少冰煮蛋器冷却",
			"desc":"冰煮蛋器冷却时间减少25秒",
			"icon":13,
			"modif":[
				{
					"card_id":["ice_egg_boiler_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-25*60
				}
			]
		}
	)
	register_cookbook(
		"mapo_tofu",
		{
			"rank":1,
			"title":"麻婆豆腐",
			"tiny_desc":"减少臭豆腐投手冷却",
			"desc":"臭豆腐投手冷却时间减少2秒",
			"icon":14,
			"modif":[
				{
					"card_id":["stinky_tofu_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"goubuli_bun",
		{
			"rank":2,
			"title":"狗不理包子",
			"tiny_desc":"减少机枪小笼包冷却",
			"desc":"机枪小笼包冷却时间减少5秒",
			"icon":15,
			"modif":[
				{
					"card_id":["gatlin_long_bao"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				}
			]
		}
	)
	register_cookbook(
		"fried_egg_with_tomato",
		{
			"rank":2,
			"title":"番茄炒蛋",
			"tiny_desc":"减少色拉投手冷却",
			"desc":"色拉投手冷却时间减少2秒",
			"icon":16,
			"modif":[
				{
					"card_id":["salad_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"lafite_limited_edition",
		{
			"rank":2,
			"title":"拉菲限量版",
			"tiny_desc":"减少三线酒架冷却",
			"desc":"三线酒架冷却时间减少1秒",
			"icon":17,
			"modif":[
				{
					"card_id":["triple_wine_rack"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	//register_cookbook(
	//	"chunky_blood_stew",
	//	{
	//		"rank":2,
	//		"title":"毛血旺",
	//		"tiny_desc":"火盆死亡爆炸",
	//		"desc":"火盆死亡后在原地生成一个酒瓶炸弹",
	//		"icon":18,
	//		"modif":[
	//		]
	//	}
	//)
	register_cookbook(
		"bread_family",
		{
			"rank":2,
			"title":"面包家族",
			"tiny_desc":"增强雷电长棍面包",
			"desc":"雷电长棍面包冷却时间减少5秒，攻击间隔减少1秒",
			"icon":19,
			"modif":[
				{
					"card_id":["lightning_baguette"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				},
				{
					"card_id":["lightning_baguette"],
					"modif_type":"cycle",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"oden",
		{
			"rank":2,
			"title":"关东煮",
			"tiny_desc":"减少关东煮喷锅和章鱼烧冷却",
			"desc":"关东煮喷锅冷却时间减少1秒\n章鱼烧冷却时间减少5秒",
			"icon":20,
			"modif":[
				{
					"card_id":["takoyaki"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				},
				{
					"card_id":["oden_pot"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"tea_egg",
		{
			"rank":2,
			"title":"茶叶蛋",
			"tiny_desc":"减少开水壶炸弹冷却",
			"desc":"开水壶炸弹冷却时间减少2秒",
			"icon":21,
			"modif":[
				{
					"card_id":["kettle_bomb"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-2*60
				}
			]
		}
	)
	register_cookbook(
		"christmas_gingerbread",
		{
			"rank":2,
			"title":"圣诞姜饼",
			"tiny_desc":"减少钢鱼刺冷却",
			"desc":"钢鱼刺冷却时间减少25秒",
			"icon":22,
			"modif":[
				{
					"card_id":["iron_fishbone"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-25*60
				}
			]
		}
	)
	register_cookbook(
		"boiled_fish",
		{
			"rank":2,
			"title":"水煮鱼",
			"tiny_desc":"减少双向水管冷却",
			"desc":"双向水管冷却时间减少1秒",
			"icon":23,
			"modif":[
				{
					"card_id":["double_water_pipe"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"beijing_shabu_pot",
		{
			"rank":2,
			"title":"老北京涮锅",
			"tiny_desc":"减少浮空三锅冷却",
			"desc":"麻辣香锅、肥牛火锅和生煎锅冷却时间减少1秒",
			"icon":24,
			"modif":[
				{
					"card_id":["spicy_pot","beef_hotpot","pan_fried_bun"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"candied_hawthorn",
		{
			"rank":2,
			"title":"冰糖葫芦",
			"tiny_desc":"减少糖葫芦炮弹冷却",
			"desc":"糖葫芦炮弹冷却时间减少1秒",
			"icon":25,
			"modif":[
				{
					"card_id":["tang_hu_lu"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
	register_cookbook(
		"seafood_platter",
		{
			"rank":2,
			"title":"海鲜大咖",
			"tiny_desc":"减少海底卡冷却",
			"desc":"炭烧海星冷却时间减少1秒\n咖喱龙虾炮冷却时间减少5秒",
			"icon":26,
			"modif":[
				{
					"card_id":["coal_starfish"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				},
				{
					"card_id":["curry_lobster_cannon"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-5*60
				}
			]
		}
	)
	register_cookbook(
		"sun_cake",
		{
			"rank":2,
			"title":"太阳饼",
			"tiny_desc":"减少大火炉冷却",
			"desc":"大火炉冷却时间减20秒",
			"icon":31,
			"modif":[
				{
					"card_id":["large_fire"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-20*60
				}
			]
		}
	)
	register_cookbook(
		"multi_cuisine",
		{
			"rank":2,
			"title":"多元料理",
			"tiny_desc":"减少勇士挑战奖励卡片冷却",
			"desc":"迷你披萨炉和全能糖球投手冷却时间减少1秒",
			"icon":36,
			"modif":[
				{
					"card_id":["pizza_oven","sugar_ball_pult"],
					"modif_type":"cooldown",
					"modif_calc":"plus",
					"amount":-1*60
				}
			]
		}
	)
}