function task_registry_init(){
	global.task_pool = ds_map_create()
}

function register_task(task_id,task_data){
	ds_map_add(global.task_pool,task_id,task_data)
}

function get_task_data(task_id){
	return ds_map_find_value(global.task_pool,task_id)
}

function task_init(){
	task_registry_init()
	{//注册所有主线任务
		register_task("main_level_0",
			{
				"type":"main_task",
				"title":"冒险家的第一战",
				"desc":"从这里开始你的冒险之旅吧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_1",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cookie_island",
						"desc":"通关一次曲奇岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_1",
			{
				"type":"main_task",
				"title":"沙拉保卫战",
				"desc":"这里的老鼠怎么这么多？算了，还是沙拉要紧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"salad_island_land",
						"desc":"通关一次色拉岛（陆）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_2",
			{
				"type":"main_task",
				"title":"水面战争",
				"desc":"是谁在这里放了一个水池？太缺德了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"salad_island_water",
						"desc":"通关一次色拉岛（水）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_3",
			{
				"type":"main_task",
				"title":"夜间保卫战",
				"desc":"好黑……居然连天上掉的火苗都没有了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mousse_island",
						"desc":"通关一次慕斯岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_4",
			{
				"type":"main_task",
				"title":"巧克力防线",
				"desc":"老鼠越来越多了，是时候让我们的高个子朋友来帮忙了。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_5",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"champagne_island_land",
						"desc":"通关一次香槟岛（陆）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_5",
			{
				"type":"main_task",
				"title":"夜间水战",
				"desc":"为什么青蛙王子要骑着自己曾经的同类？真是令人不解。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_6",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"champagne_island_water",
						"desc":"通关一次香槟岛（水）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":15
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_6",
			{
				"type":"main_task",
				"title":"探秘神殿",
				"desc":"隐秘的神殿深处，供奉的又是何方神圣？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_7",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":1500
					}
				]
			}
		)
		register_task("main_level_7",
			{
				"type":"main_task",
				"title":"堵洞行动",
				"desc":"真是太离谱了！它们居然把老鼠洞打到野餐布上来了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_8",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pudding_island_daytime",
						"desc":"通关一次布丁岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2000
					}
				]
			}
		)
		register_task("main_level_8",
			{
				"type":"main_task",
				"title":"夜间野餐",
				"desc":"鼹鼠是干什么的？应该是挖鼠夹的吧",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_9",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pudding_island_night",
						"desc":"通关一次布丁岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2000
					}
				]
			}
		)
		register_task("main_level_9",
			{
				"type":"main_task",
				"title":"双水道战争",
				"desc":"这里就是传说中的反转泳池吗？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_10",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cocoa_island_daytime",
						"desc":"通关一次可可岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2000
					}
				]
			}
		)
		register_task("main_level_10",
			{
				"type":"main_task",
				"title":"大战蝙蝠侠",
				"desc":"蝙蝠侠没见到，倒是见到小偷了……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_11",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cocoa_island_night",
						"desc":"通关一次可可岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2250
					}
				]
			}
		)
		register_task("main_level_11",
			{
				"type":"main_task",
				"title":"大雾退散",
				"desc":"退！退！退！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_12",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"curry_island_daytime",
						"desc":"通关一次咖喱岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2250
					}
				]
			}
		)
		register_task("main_level_12",
			{
				"type":"main_task",
				"title":"垃圾处理",
				"desc":"可可岛（雾水）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_13",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"curry_island_night",
						"desc":"通关一次咖喱岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2250
					}
				]
			}
		)
		register_task("main_level_13",
			{
				"type":"main_task",
				"title":"决战深渊",
				"desc":"这里就是最后一关了吗？也不过如此吧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_14",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":150
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":5000
					}
				]
			}
		)
		register_task("main_level_14",
			{
				"type":"main_task",
				"title":"洗碗池战争",
				"desc":"为什么一个洗碗池的BGM会这么燃？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_15",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mustard_cottage_daytime",
						"desc":"通关一次芥末小屋（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("main_level_15",
			{
				"type":"main_task",
				"title":"章鱼小丸子的诱惑",
				"desc":"保罗是什么？我只知道章鱼小丸子很好吃……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_16",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mustard_cottage_night",
						"desc":"通关一次芥末小屋（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("main_level_16",
			{
				"type":"main_task",
				"title":"横行霸道",
				"desc":"据说螃蟹只能横着走……不对，它怎么还能遁地？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_17",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mint_beach_daytime",
						"desc":"通关一次薄荷海滩（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":15
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":3000
					}
				]
			}
		)
		register_task("main_level_17",
			{
				"type":"main_task",
				"title":"夜会金发美人",
				"desc":"下次我再看见螃蟹时，我只希望它背上不要坐着一只金发老鼠……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_18",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mint_beach_night",
						"desc":"通关一次薄荷海滩（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":15
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":3000
					}
				]
			}
		)
		register_task("main_level_18",
			{
				"type":"main_task",
				"title":"偷芝士的小老鼠",
				"desc":"潮水已然退去",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_19",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":3
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":10000
					}
				]
			}
		)
		register_task("main_level_19",
			{
				"type":"main_task",
				"title":"雨林烧烤",
				"desc":"地上坑坑洼洼的，满身都是泥。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_20",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"charcoal_jungle_daytime",
						"desc":"通关一次炭烧雨林（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":15
					},
					{
						"type":"gold",
						"amount":6000
					}
				]
			}
		)
		register_task("main_level_20",
			{
				"type":"main_task",
				"title":"有味道的“使”者",
				"desc":"禁止随地大小便！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_21",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"charcoal_jungle_night",
						"desc":"通关一次炭烧雨林（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":15
					},
					{
						"type":"gold",
						"amount":6000
					}
				]
			}
		)
		register_task("main_level_21",
			{
				"type":"main_task",
				"title":"庄园探秘",
				"desc":"说好的抹茶呢，怎么给我放到吸血鬼庄园里了",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_22",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"matcha_manor_daytime",
						"desc":"通关一次抹茶庄园（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":15
					},
					{
						"type":"gold",
						"amount":8000
					}
				]
			}
			
		)
		register_task("main_level_22",
			{
				"type":"main_task",
				"title":"吸血男爵",
				"desc":"男爵会召唤蝙蝠？都是啮齿目动物，好像也挺合理的……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_23",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"matcha_manor_night",
						"desc":"通关一次抹茶庄园（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":25
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":15
					},
					{
						"type":"gold",
						"amount":8000
					}
				]
			}
			
		)
		register_task("main_level_23",
			{
				"type":"main_task",
				"title":"港口突袭",
				"desc":"迷雾怎么又来了？也许我得随身带点火柴……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_24",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"macchiato_port",
						"desc":"通关一次玛奇朵港",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
			
		)
		register_task("main_level_24",
			{
				"type":"main_task",
				"title":"棉花高地",
				"desc":"这里的云真的能吃吗？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_25",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cotton_candy_sky_daytime",
						"desc":"通关一次棉花糖天空（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
			
		)
		register_task("main_level_25",
			{
				"type":"main_task",
				"title":"晴空之夜",
				"desc":"也许我该研究一下棉花糖是怎么承受我的重量的……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_26",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cotton_candy_sky_night",
						"desc":"通关一次棉花糖天空（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
			
		)
		register_task("main_level_26",
			{
				"type":"main_task",
				"title":"高温果酱",
				"desc":"谁能告诉我为什么果酱会有这么高的温度？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_27",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"jam_tribe_daytime",
						"desc":"通关一次果酱部落（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
			
		)
		register_task("main_level_27",
			{
				"type":"main_task",
				"title":"杰克来也",
				"desc":"能自我拆解的石头人？真有意思。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_28",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"jam_tribe_daytime",
						"desc":"通关一次果酱部落（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":1
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
			
		)
		register_task("main_level_28",
			{
				"type":"main_task",
				"title":"决战火山之巅",
				"desc":"说得我都想点一杯雪顶咖啡了……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_29",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"snowcap_volcano",
						"desc":"通关一次雪顶火山）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":60
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":100000
					}
				]
			}
			
		)
		register_task("main_level_29",
			{
				"type":"main_task",
				"title":"白日竹筏",
				"desc":"茴香竹筏（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_30",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"fennel_raft_daytime",
						"desc":"通关一次茴香竹筏（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":50000
					}
				]
			}
			
		)
		register_task("main_level_30",
			{
				"type":"main_task",
				"title":"黑夜竹筏",
				"desc":"茴香竹筏（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_31",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"fennel_raft_night",
						"desc":"通关一次茴香竹筏（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":35
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":50000
					}
				]
			}
			
		)
		register_task("main_level_31",
			{
				"type":"main_task",
				"title":"白日断桥",
				"desc":"孜然断桥（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_32",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cumin_bridge_daytime",
						"desc":"通关一次孜然断桥（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":50000
					}
				]
			}
			
		)
		register_task("main_level_32",
			{
				"type":"main_task",
				"title":"黑夜断桥",
				"desc":"孜然断桥（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_33",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cumin_bridge_night",
						"desc":"通关一次孜然断桥（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":45
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":50000
					}
				]
			}
			
		)
		register_task("main_level_33",
			{
				"type":"main_task",
				"title":"卤料花园",
				"desc":"卤料花园",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_34",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"marinade_garden",
						"desc":"通关一次卤料花园",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":100
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":5
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":50
					},
					{
						"type":"gold",
						"amount":150000
					}
				]
			}
			
		)
		register_task("main_level_34",
			{
				"type":"main_task",
				"title":"白日月桂",
				"desc":"月桂天空（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_35",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"laurel_sky_daytime",
						"desc":"通关一次月桂天空（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":15
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":1
					},
					{
						"type":"gold",
						"amount":80000
					}
				]
			}
			
		)
		register_task("main_level_35",
			{
				"type":"main_task",
				"title":"黑夜月桂",
				"desc":"月桂天空（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_36",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"laurel_sky_night",
						"desc":"通关一次月桂天空（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":1
					},
					{
						"type":"gold",
						"amount":80000
					}
				]
			}
			
		)
		register_task("main_level_36",
			{
				"type":"main_task",
				"title":"白日空港",
				"desc":"香叶空港（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_37",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"bayleaf_airport_daytime",
						"desc":"通关一次香叶空港（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":25
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":1
					},
					{
						"type":"gold",
						"amount":80000
					}
				]
			}
			
		)
		register_task("main_level_37",
			{
				"type":"main_task",
				"title":"黑夜空港",
				"desc":"香叶空港（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_38",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"bayleaf_airport_night",
						"desc":"通关一次香叶空港（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":1
					},
					{
						"type":"gold",
						"amount":80000
					}
				]
			}
			
		)
		register_task("main_level_38",
			{
				"type":"main_task",
				"title":"香料飞船",
				"desc":"香料飞船",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_39",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spice_airship",
						"desc":"通关一次香料飞船",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":60
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":3
					},
					{
						"type":"gold",
						"amount":180000
					}
				]
			}
			
		)
		register_task("main_level_39",
			{
				"type":"main_task",
				"title":"白日浮岛",
				"desc":"花椒浮岛（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_40",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pepper_floating_isle_daytime",
						"desc":"通关一次花椒浮岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":35
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
					{
						"type":"gold",
						"amount":85000
					}
				]
			}
			
		)
		register_task("main_level_40",
			{
				"type":"main_task",
				"title":"黑夜浮岛",
				"desc":"花椒浮岛（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_41",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pepper_floating_isle_night",
						"desc":"通关一次花椒浮岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":35
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
					{
						"type":"gold",
						"amount":85000
					}
				]
			}
			
		)
		register_task("main_level_41",
			{
				"type":"main_task",
				"title":"白日彩虹",
				"desc":"丁香彩虹（日）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_42",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"lilac_rainbow_daytime",
						"desc":"通关一次丁香彩虹（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
					{
						"type":"gold",
						"amount":95000
					}
				]
			}
			
		)
		register_task("main_level_42",
			{
				"type":"main_task",
				"title":"黑夜彩虹",
				"desc":"丁香彩虹（夜）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_43",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"lilac_rainbow_night",
						"desc":"通关一次丁香彩虹（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
					{
						"type":"gold",
						"amount":95000
					}
				]
			}
			
		)
		register_task("main_level_43",
			{
				"type":"main_task",
				"title":"十三香中心岛",
				"desc":"十三香中心岛",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_44",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spices_central_isle",
						"desc":"通关一次十三香中心岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_6",
						"amount":1
					},
					{
						"type":"gold",
						"amount":150000
					}
				]
			}
			
		)
		register_task("main_level_44",
			{
				"type":"main_task",
				"title":"未至约期",
				"desc":"这个主线任务还没有开放。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_45",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"sugar_space_station",
						"desc":"请等待星际穿越开启",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":0
					},
					{
						"type":"gold",
						"amount":0
					}
				]
			}
			
		)
	}
	{//注册所有支线任务
		register_task("card_upgrade_1",
			{
				"type":"side_task",
				"title":"增强实力-1",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_2",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":1,
						"desc":"将一张卡片强化至1星",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("card_upgrade_2",
			{
				"type":"side_task",
				"title":"增强实力-2",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_3",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":2,
						"desc":"将5张卡片强化至2星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":5
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("card_upgrade_3",
			{
				"type":"side_task",
				"title":"增强实力-3",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_4",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":4,
						"desc":"将3张卡片强化至4星",
						"require":3,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2000
					}
				]
			}
		)
		register_task("card_upgrade_4",
			{
				"type":"side_task",
				"title":"增强实力-4",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_5",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":6,
						"desc":"将5张卡片强化至6星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":10
					},
					{
						"type":"gold",
						"amount":10000
					}
				]
			}
		)
		register_task("card_upgrade_5",
			{
				"type":"side_task",
				"title":"增强实力-5",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_6",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":7,
						"desc":"将5张卡片强化至7星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
		)
		register_task("card_upgrade_6",
			{
				"type":"side_task",
				"title":"增强实力-6",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_7",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":8,
						"desc":"将5张卡片强化至8星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":5
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
		)
		register_task("card_upgrade_7",
			{
				"type":"side_task",
				"title":"增强实力-7",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_8",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":9,
						"desc":"将5张卡片强化至9星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":2
					},
					{
						"type":"gold",
						"amount":30000
					}
				]
			}
		)
		register_task("card_upgrade_8",
			{
				"type":"side_task",
				"title":"增强实力-8",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_9",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":10,
						"desc":"将5张卡片强化至10星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":5
					},
					{
						"type":"gold",
						"amount":50000
					}
				]
			}
		)
		register_task("card_upgrade_9",
			{
				"type":"side_task",
				"title":"增强实力-9",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_10",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":11,
						"desc":"将4张卡片强化至11星",
						"require":4,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"clover_6",
						"amount":3
					},
					{
						"type":"gold",
						"amount":80000
					}
				]
			}
		)
		register_task("card_upgrade_10",
			{
				"type":"side_task",
				"title":"增强实力-10",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_11",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":12,
						"desc":"将4张卡片强化至12星",
						"require":3,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_6",
						"amount":5
					},
					{
						"type":"gold",
						"amount":100000
					}
				]
			}
		)
		register_task("card_upgrade_11",
			{
				"type":"side_task",
				"title":"增强实力-11",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_12",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":13,
						"desc":"将3张卡片强化至13星",
						"require":3,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"elven_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_S",
						"amount":2
					},
					{
						"type":"gold",
						"amount":120000
					}
				]
			}
		)
		register_task("card_upgrade_12",
			{
				"type":"side_task",
				"title":"增强实力-12",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_13",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":20,
						"desc":"请等待后续开放更高星级",
						"require":10,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":0
					},
					{
						"type":"gold",
						"amount":0
					}
				]
			}
		)
		register_task("undersea_level_0",
			{
				"type":"side_task",
				"title":"海底历险记",
				"desc":"获取苏打气泡，开始你的海底旋涡之旅。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"none",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"tuna_current",
						"desc":"通关金枪鱼洋流，获取苏打气泡",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":30
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
		)
	}
	{//注册所有挑战任务
		register_task("flame_save_1",
			{
				"type":"challenge_task",
				"title":"神殿节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余3500以上的火苗",
						"require":3500,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":10000
					}
				]
			}
		)
		register_task("flame_save_2",
			{
				"type":"challenge_task",
				"title":"深渊节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余3500以上的火苗",
						"require":3500,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":15000
					}
				]
			}
		)
		register_task("flame_save_3",
			{
				"type":"challenge_task",
				"title":"芝士城堡节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余5000以上的火苗",
						"require":5000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
		)
		register_task("flame_save_4",
			{
				"type":"challenge_task",
				"title":"玛奇朵港节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_5",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"macchiato_port",
						"desc":"通关一次玛奇朵港",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余5500以上的火苗",
						"require":5500,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":15
					},
					{
						"type":"gold",
						"amount":25000
					}
				]
			}
		)
		register_task("flame_save_5",
			{
				"type":"challenge_task",
				"title":"雪顶火山节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_6",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"snowcap_volcano",
						"desc":"通关一次雪顶火山",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余6000以上的火苗",
						"require":6000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":30
					},
					{
						"type":"gold",
						"amount":30000
					}
				]
			}
		)
		register_task("flame_save_6",
			{
				"type":"challenge_task",
				"title":"卤料花园节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_7",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"marinade_garden",
						"desc":"通关一次卤料花园",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余8000以上的火苗",
						"require":8000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":50
					},
					{
						"type":"gold",
						"amount":35000
					}
				]
			}
		)
		register_task("flame_save_7",
			{
				"type":"challenge_task",
				"title":"香料飞船节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_8",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spice_airship",
						"desc":"通关一次香料飞船",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余10000以上的火苗",
						"require":10000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"gold",
						"amount":40000
					}
				]
			}
		)
		register_task("flame_save_8",
			{
				"type":"challenge_task",
				"title":"十三香中心岛节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_9",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spices_central_isle",
						"desc":"通关一次十三香中心岛",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余12000以上的火苗",
						"require":12000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":60000
					}
				]
			}
		)
		register_task("flame_save_9",
			{
				"type":"challenge_task",
				"title":"未开放的节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_10",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"hamburger_king_star",
						"desc":"请等待星际穿越开启",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余0以上的火苗",
						"require":0,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":0
					},
					{
						"type":"gold",
						"amount":0
					}
				]
			}
		)
		register_task("perfect_challenge_1",
			{
				"type":"challenge_task",
				"title":"完美挑战-1",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"card_loss",
						"desc":"不得损失超过20张卡片",
						"require":20,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":60
					},
					{
						"type":"gold",
						"amount":5000
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":5
					},
				]
			}
		)
		register_task("perfect_challenge_2",
			{
				"type":"challenge_task",
				"title":"完美挑战-2",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"card_loss",
						"desc":"不得损失超过45张卡片",
						"require":45,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":10000
					},
					{
						"type":"item",
						"item_id":"clover_2",
						"amount":5
					},
				]
			}
		)
		register_task("perfect_challenge_3",
			{
				"type":"challenge_task",
				"title":"完美挑战-3",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过600秒",
						"require":600,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":100
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":50
					},
					{
						"type":"gold",
						"amount":10000
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":5
					},
				]
			}
		)
		register_task("perfect_challenge_4",
			{
				"type":"challenge_task",
				"title":"完美挑战-4",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_5",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"macchiato_port",
						"desc":"通关一次玛奇朵港",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过480秒",
						"require":480,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":20
					},
					{
						"type":"gold",
						"amount":15000
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":2
					},
				]
			}
		)
		register_task("perfect_challenge_5",
			{
				"type":"challenge_task",
				"title":"完美挑战-5",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_6",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"snowcap_volcano",
						"desc":"通关一次雪顶火山",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过540秒",
						"require":540,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":150
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":50
					},
					{
						"type":"gold",
						"amount":50000
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":2
					},
				]
			}
		)
		register_task("perfect_challenge_6",
			{
				"type":"challenge_task",
				"title":"完美挑战-6",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_7",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"marinade_garden",
						"desc":"通关一次卤料花园",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过540秒",
						"require":540,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":200
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":60
					},
					{
						"type":"gold",
						"amount":20000
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":5
					},
				]
			}
		)
		register_task("perfect_challenge_7",
			{
				"type":"challenge_task",
				"title":"完美挑战-7",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_8",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spice_airship",
						"desc":"通关一次香料飞船",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过540秒",
						"require":540,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_6",
						"amount":1
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
		)
		register_task("perfect_challenge_8",
			{
				"type":"challenge_task",
				"title":"完美挑战-8",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_9",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spices_central_isle",
						"desc":"通关一次十三香中心岛",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过660秒",
						"require":660,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"elven_spices",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":40
					},
					{
						"type":"item",
						"item_id":"clover_S",
						"amount":1
					},
					{
						"type":"gold",
						"amount":25000
					}
				]
			}
		)
		register_task("perfect_challenge_9",
			{
				"type":"challenge_task",
				"title":"完美挑战-9",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_10",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"hamburger_king_star",
						"desc":"请等待星际穿越开启",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"time_limit",
						"desc":"通关时间不超过0秒",
						"require":0,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":0
					},
					{
						"type":"gold",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":0
					},
				]
			}
		)
		register_task("hardcore_challenge_1",
			{
				"type":"challenge_task",
				"title":"极限挑战-1",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("hardcore_challenge_2",
			{
				"type":"challenge_task",
				"title":"极限挑战-2",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":30
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":5
					},
					{
						"type":"gold",
						"amount":7500
					}
				]
			}
		)
		register_task("hardcore_challenge_3",
			{
				"type":"challenge_task",
				"title":"极限挑战-3",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":120
					},
					{
						"type":"gold",
						"amount":10000
					},
					{
						"type":"item",
						"item_id":"less_crystal",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":1
					},
				]
			}
		)
		register_task("hardcore_challenge_4",
			{
				"type":"challenge_task",
				"title":"极限挑战-4",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_5",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"macchiato_port",
						"desc":"通关一次玛奇朵港",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":30
					},
					{
						"type":"gold",
						"amount":12000
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":2
					},
				]
			}
		)
		register_task("hardcore_challenge_5",
			{
				"type":"challenge_task",
				"title":"极限挑战-5",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_6",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"snowcap_volcano",
						"desc":"通关一次雪顶火山",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":100
					},
					{
						"type":"gold",
						"amount":25000
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":20
					},
				]
			}
		)
		register_task("hardcore_challenge_6",
			{
				"type":"challenge_task",
				"title":"极限挑战-6",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_7",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"marinade_garden",
						"desc":"通关一次卤料花园",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":150
					},
					{
						"type":"gold",
						"amount":15000
					},
					{
						"type":"item",
						"item_id":"middle_crystal",
						"amount":50
					},
					{
						"type":"item",
						"item_id":"clover_4",
						"amount":10
					},
				]
			}
		)
		register_task("hardcore_challenge_7",
			{
				"type":"challenge_task",
				"title":"极限挑战-7",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_8",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spice_airship",
						"desc":"通关一次香料飞船",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":60
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":10
					},
					{
						"type":"item",
						"item_id":"clover_5",
						"amount":5
					},
					{
						"type":"gold",
						"amount":20000
					}
				]
			}
		)
		register_task("hardcore_challenge_8",
			{
				"type":"challenge_task",
				"title":"极限挑战-8",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_9",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"spices_central_isle",
						"desc":"通关一次十三香中心岛",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"magical_spices",
						"amount":80
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":20
					},
					{
						"type":"item",
						"item_id":"clover_6",
						"amount":5
					},
					{
						"type":"gold",
						"amount":25000
					}
				]
			}
		)
		register_task("hardcore_challenge_9",
			{
				"type":"challenge_task",
				"title":"极限挑战-9",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_10",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"hamburger_king_star",
						"desc":"请等待星际穿越开启",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何一次性的伤害类卡片",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"royal_spices",
						"amount":0
					},
					{
						"type":"gold",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"advanced_crystal",
						"amount":0
					},
					{
						"type":"item",
						"item_id":"clover_3",
						"amount":0
					},
				]
			}
		)
	}
}